### ISSUE TITLE
SR: erro de LazyInitializationException ao fechar solicitação

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#1021]
Erro ao tentar fechar solicitação:

`Caused by: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role:
br.gov.jfrj.siga.sr.model.SrItemConfiguracao.meuItemHistoricoSet, could not initialize proxy - no Session
at
org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersist
entCollection.java:569)
at
org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentC
ollection.java:188)
at
org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:548
)
at
org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:126)
at org.hibernate.collection.internal.PersistentBag.get(PersistentBag.java:439)
at br.gov.jfrj.siga.sr.model.SrItemConfiguracao.getAtual(SrItemConfiguracao.java:198)
at br.gov.jfrj.siga.sr.model.SrConfiguracaoBL.deduzFiltro(SrConfiguracaoBL.java:43)
at
br.gov.jfrj.siga.sr.model.SrConfiguracaoBL.listarConfiguracoesAtivasPorFiltro(SrConfiguracaoBL.java:108)
at br.gov.jfrj.siga.sr.model.SrConfiguracao.listar(SrConfiguracao.java:482)
at br.gov.jfrj.siga.sr.model.SrConfiguracao.listar(SrConfiguracao.java:478)
at br.gov.jfrj.siga.sr.model.SrMovimentacao.atualizarAcordos(SrMovimentacao.java:478)
at br.gov.jfrj.siga.sr.model.SrMovimentacao.checarCampos(SrMovimentacao.java:457)
at br.gov.jfrj.siga.sr.model.SrMovimentacao.salvarAtualizandoSolicitacao(SrMovimentacao.java:349)
at br.gov.jfrj.siga.sr.model.SrMovimentacao.salvar(SrMovimentacao.java:340)
at br.gov.jfrj.siga.sr.model.SrSolicitacao.fechar(SrSolicitacao.java:2249)
at br.gov.jfrj.siga.sr.vraptor.SolicitacaoController.fecharGravar(SolicitacaoController.java:617)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at
br.com.caelum.vraptor.interceptor.ExecuteMethodInterceptor.intercept(ExecuteMethodInterceptor.java:61)`

**Comment by rafaela00castro** [comment]
Analisando o código, o método `fechar()` da classe SrSolicitacao precisa buscar o item e a ação na integra no banco antes de setá-los na movimentação, pois eles somente são objetos preenchidos com id, sigla, e descrição através do "http post", e para o usar o `getAtual()` é necessário ter toda a instância inicializada (ou pelo menos o `meuItemHistoricoSet`).

**Comment by rafaela00castro** [comment]
Outra coisa estranha é que o exibir não está "pegando" o registro mais atual do item

![captura_de_tela_072716_063036_pm](https://cloud.githubusercontent.com/assets/8461113/17193184/36b58c1e-5428-11e6-8b40-a1e8ddafd978.jpg)

Isso poderia evitar o erro no fechamento, que já teria o item mais atual e não tentaria "pegá-lo" nesse momento.
