### ISSUE TITLE
SR: erro lazy initialization (LIE) ao buscar SrItemConfiguracao.meuItemHistoricoSet

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#1077]
Ocorre erro ao tentar gravar/reclassificar/escalonar/fechar

`org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: br.gov.jfrj.siga.sr.model.SrItemConfiguracao.meuItemHistoricoSet, could not initialize proxy - no Session
	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:566)
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:186)
	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:545)
	at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:124)
	at org.hibernate.collection.internal.PersistentBag.get(PersistentBag.java:439)
	at br.gov.jfrj.siga.sr.model.SrItemConfiguracao.getAtual(SrItemConfiguracao.java:198)
	at br.gov.jfrj.siga.sr.model.SrConfiguracaoBL.deduzFiltro(SrConfiguracaoBL.java:43)
	at br.gov.jfrj.siga.cp.bl.CpConfiguracaoBL.buscaConfiguracao(CpConfiguracaoBL.java:308)
	at br.gov.jfrj.siga.sr.model.SrConfiguracao.buscar(SrConfiguracao.java:454)
	at br.gov.jfrj.siga.sr.model.SrConfiguracao.buscarAssociacao(SrConfiguracao.java:469)
	at br.gov.jfrj.siga.sr.model.SrSolicitacao.getAtributoAssociados(SrSolicitacao.java:835)
	at br.gov.jfrj.siga.sr.model.SrSolicitacao.getObrigatoriedadeTiposAtributoAssociados(SrSolicitacao.java:813)
	at br.gov.jfrj.siga.sr.vraptor.SolicitacaoController.validarFormReclassificar(SolicitacaoController.java:348)
	at br.gov.jfrj.siga.sr.vraptor.SolicitacaoController.escalonarGravar(SolicitacaoController.java:736)
`

**Comment by rafaela00castro** [comment]
hotfix [v.5.3.4.1](https://github.com/projeto-siga/siga/releases/tag/5.3.4.1)

**Comment by rafaela00castro** [comment]
Ao realizar testes usando solicitações mais antigas, em algumas solicitações comecei a receber esse erro de LazyInitializationException. Isso ocorreu pq essas solicitações foram criadas com um determinado item e posteriormente, esse item foi atualizado, criando um novo registro no banco. Como o item passou a ter um histórico, ocorria esse erro ao buscar o item atual ( `item.getAtual()` ) para validar a classificação (item, ação e atributos).

Para resolver o erro foi necessário buscar "na íntegra" o item e a ação através dos ID's passados na requisição. Assim ao buscar o histórico do item, ele possui toda a instância com as informações recuperadas.
