### ISSUE TITLE
SR: NPE ao cadastrar atributo

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#1115]
```
java.lang.NullPointerException
	at br.gov.jfrj.siga.sr.model.SrAtributo.hashCode(SrAtributo.java:186)
	at java.util.HashMap.hash(HashMap.java:362)
	at java.util.HashMap.put(HashMap.java:492)
	at java.util.HashSet.add(HashSet.java:217)
	at br.gov.jfrj.siga.model.Objeto.saveAndCascade(Objeto.java:195)
	at br.gov.jfrj.siga.model.Objeto.save(Objeto.java:110)
	at br.gov.jfrj.siga.cp.model.HistoricoSuporte.salvarComHistorico(HistoricoSuporte.java:142)
	at br.gov.jfrj.siga.sr.model.SrAtributo.salvar(SrAtributo.java:168)
	at br.gov.jfrj.siga.sr.vraptor.AtributoController.gravarAtributo(AtributoController.java:73)
```

**Comment by rafaela00castro** [comment]
Problema na função de `hashCode()`. Ela também é chamada ao criar um atributo por conta do trecho `avoidCascadeSaveLoops.get().add(this);` no Objeto.java.  Nesse momento, o atributo ainda não possui a informação de qual é o seu id inicial. Nesse caso, usar o próprio ID, já que no primeiro cadastro ele tb é o ID_INICAL
