### ISSUE TITLE
SR: NPE ao visualizar algumas solicitações

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#1139]
`java.lang.NullPointerException
	at br.gov.jfrj.siga.sr.model.SrAtributoSolicitacao.equals(SrAtributoSolicitacao.java:184)
	at java.util.HashMap.put(HashMap.java:496)
	at java.util.HashSet.add(HashSet.java:217)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:342)
	at br.gov.jfrj.siga.sr.model.SrSolicitacao.getAtributoSolicitacaoSet(SrSolicitacao.java:424)
	at br.gov.jfrj.siga.sr.model.SrSolicitacao.getAtributoSolicitacaoSetAtual(SrSolicitacao.java:413)
	at br.gov.jfrj.siga.sr.vraptor.SolicitacaoController.exibir(SolicitacaoController.java:409)
	at sun.reflect.GeneratedMethodAccessor411.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)`

**Comment by rafaela00castro** [comment]
Antigamente os atributos da solicitação eram gravados mesmo se fossem `null`. Esse erro ocorre quando: 

- solicitação possui pelo menos 1 atributo `null` e outros atributos

- solicitação principal possui pelo menos 1 atributo `null` e possui solicitações filhas com pelo menos 1 atributo, já que o padrão é exibir todo o contexto (exibir atributo da solicitação além dos atributos das solicitações filhas, se tiver)

- solicitação principal com atributos e possui solicitação filha com pelo menos 1 atributo `null`, já que o padrão é exibir todo o contexto 

Existem ponto de erro em dois métodos: `getAtributoSolicitacaoSet` e `buscarAtributosAtuais`. Como eles usam a interface `Set`, ao chamar o método `equals` para verificar se o objeto é único para ser inserido na coleção é disparada a exception já que o `null` é enviado para comparação.
