### ISSUE TITLE
SR: erro ao abrir solicitação no IE na versão 5.3.10.1

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#1149]
Erro reportado pelo @luiz-antonio quando ele tentou abrir a solicitação TRF2-SR-2017/40911 no IE. 
![captura_de_tela_020717_040421_pm](https://cloud.githubusercontent.com/assets/8461113/22705866/52ed2ba6-ed54-11e6-8048-27c5f52a1946.jpg)

Ele conseguiu abrir a solicitação no Chrome. Fizemos testes, e também funciona no Firefox.

**Comment by rafaela00castro** [comment]
Erro no Jboss:
```
16:04:09,551 INFO  [br.com.caelum.vraptor.interceptor.multipart.CommonsUploadMultipartInterceptor] (http-localhost/127.0.0.1:8080-2) Request contains multipart data. Try to parse with commons-upload.
16:04:09,562 WARN  [br.com.caelum.vraptor.interceptor.multipart.CommonsUploadMultipartInterceptor] (http-localhost/127.0.0.1:8080-2) There was some problem parsing this multipart request, or someone is not sending a RFC1867 compatible multipart request.: org.apache.commons.fileupload.FileUploadException: Stream ended unexpectedly
	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:362) [commons-fileupload-1.3.1.jar:1.3.1]
	at org.apache.commons.fileupload.servlet.ServletFileUpload.parseRequest(ServletFileUpload.java:115) [commons-fileupload-1.3.1.jar:1.3.1]
	at br.com.caelum.vraptor.interceptor.multipart.CommonsUploadMultipartInterceptor.intercept(CommonsUploadMultipartInterceptor.java:103) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
	at br.gov.jfrj.siga.sr.interceptor.HandleCorreioInterceptor.intercept(HandleCorreioInterceptor.java:26) [classes:]
...

Caused by: org.apache.commons.fileupload.MultipartStream$MalformedStreamException: Stream ended unexpectedly
	at org.apache.commons.fileupload.MultipartStream.readHeaders(MultipartStream.java:540) [commons-fileupload-1.3.1.jar:1.3.1]
	at org.apache.commons.fileupload.FileUploadBase$FileItemIteratorImpl.findNextItem(FileUploadBase.java:1038) [commons-fileupload-1.3.1.jar:1.3.1]
	at org.apache.commons.fileupload.FileUploadBase$FileItemIteratorImpl.hasNext(FileUploadBase.java:1106) [commons-fileupload-1.3.1.jar:1.3.1]
	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:339) [commons-fileupload-1.3.1.jar:1.3.1]
	... 48 more
```

**Comment by rafaela00castro** [comment]
Erro provocado pelo commit [c3e954a](https://github.com/projeto-siga/siga/commit/c3e954a9790e37530a5132862bc3a0695ed109df) tratado na issue #1128. A alteração nesse commit consistiu em mudar a forma de envio dos dados, passando a usar [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects) e assim considerar os arquivos no envio do formulário através de requisições Ajax.

**Comment by rafaela00castro** [comment]
De acordo com a [issue aberta para Microsoft ](https://connect.microsoft.com/IE/Feedback/Details/868498), esse problema no IE (Multipart form data is malformed) ocorre se existe algum campo sem o atributo nome sendo submetido via FormData por Ajax. Mas mesmo inserindo o nome nos input type="checkbox" não funcionou. A Microsoft fechou a issue em 2016 informando que esse problema foi corrigido no novo navegador deles (Edge).

Solução de contorno aplicada seguindo a lógica explicada [nesse artigo](https://blog.yorkxin.org/2014/02/06/ajax-with-formdata-is-broken-on-ie10-ie11). Inverti no `checkbox.tag`, o lugar do `input type="hidden"` com o `input type="checkbox"`. Assim, no caso da tela de abertura de solicitação o input hidden será o último input a ser enviado e não dá erro....vai entender =/
