### ISSUE TITLE
DOC: erro para gravar Formulário SGP: Declaração de Ajusta Anual de IRPF

### ISSUE THREAD

**Issue by adrigrassi** [projeto-siga/siga#1181]
Ao clicar no radiobutton (var tipoFormulario) retorna o seguinte erro: 

javax.servlet.ServletException: javax.servlet.ServletException: your controller raised an exception
	at br.gov.jfrj.siga.hibernate.ExThreadFilter.doFiltro(ExThreadFilter.java:67)
	at br.gov.jfrj.siga.base.auditoria.filter.ThreadFilter.doFilter(ThreadFilter.java:190)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at br.gov.jfrj.siga.base.log.RequestLoggerFilter.doFilter(RequestLoggerFilter.java:25)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
	at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.event(JBossWebContext.java:91)
	at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.invoke(JBossWebContext.java:72)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:512)
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.servlet.ServletException: your controller raised an exception
	at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:105)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at br.gov.jfrj.siga.hibernate.ExThreadFilter.executaFiltro(ExThreadFilter.java:94)
	at br.gov.jfrj.siga.hibernate.ExThreadFilter.doFiltro(ExThreadFilter.java:60)
	... 20 more
Caused by: br.com.caelum.vraptor.proxy.ProxyInvocationException: javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.el.ELException: JBWEB006003: Cannot convert [1, , ] of type class java.lang.String to class java.lang.Long
	at br.gov.jfrj.siga.vraptor.SigaLogicResult$1.intercept(SigaLogicResult.java:120)
	at br.com.caelum.vraptor.proxy.JavassistProxifier$2.invoke(JavassistProxifier.java:95)
	at br.gov.jfrj.siga.vraptor.ExDocumentoController_$$_jvst81c_3f.edita(ExDocumentoController_$$_jvst81c_3f.java)
	at br.gov.jfrj.siga.vraptor.ExDocumentoController.recarregar(ExDocumentoController.java:411)
	at sun.reflect.GeneratedMethodAccessor1352.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at br.com.caelum.vraptor.interceptor.ExecuteMethodInterceptor.intercept(ExecuteMethodInterceptor.java:61)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.ExceptionHandlerInterceptor.intercept(ExceptionHandlerInterceptor.java:67)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.ParametersInstantiatorInterceptor.intercept(ParametersInstantiatorInterceptor.java:96)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:59)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.multipart.CommonsUploadMultipartInterceptor.intercept(CommonsUploadMultipartInterceptor.java:137)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.InstantiateInterceptor.intercept(InstantiateInterceptor.java:48)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.gov.jfrj.siga.vraptor.AplicacaoExceptionInterceptor.intercept(AplicacaoExceptionInterceptor.java:39)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:56)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.util.jpa.JPATransactionInterceptor.intercept(JPATransactionInterceptor.java:54)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.gov.jfrj.siga.vraptor.CacheControlInterceptor.intercept(CacheControlInterceptor.java:44)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.ResourceLookupInterceptor.intercept(ResourceLookupInterceptor.java:69)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.EnhancedRequestExecution.execute(EnhancedRequestExecution.java:44)
	at br.com.caelum.vraptor.VRaptor$1.insideRequest(VRaptor.java:95)
	at br.com.caelum.vraptor.ioc.guice.GuiceProvider.provideForRequest(GuiceProvider.java:82)
	at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:101)
	... 24 more
Caused by: javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.el.ELException: JBWEB006003: Cannot convert [1, , ] of type class java.lang.String to class java.lang.Long
	at org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:844)
	at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:777)
	at org.apache.jsp.WEB_002dINF.page.exDocumento.edita_jsp._jspService(edita_jsp.java:153)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:365)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:309)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:242)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:832)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:620)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:553)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:482)
	at br.gov.jfrj.siga.vraptor.SigaLogicResult$1.intercept(SigaLogicResult.java:111)
	... 69 more
Caused by: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.el.ELException: JBWEB006003: Cannot convert [1, , ] of type class java.lang.String to class java.lang.Long
	at org.apache.jsp.WEB_002dINF.page.exDocumento.edita_jsp$Helper.invoke(edita_jsp.java:3333)
	at org.apache.jsp.tag.meta.http_003a.localhost.jeetags.span_tag.doTag(span_tag.java:97)
	at org.apache.jsp.WEB_002dINF.page.exDocumento.edita_jsp._jspx_meth_siga_005fspan_005f3(edita_jsp.java:2796)
	at org.apache.jsp.WEB_002dINF.page.exDocumento.edita_jsp._jspx_meth_c_005fif_005f23(edita_jsp.java:2764)
	at org.apache.jsp.WEB_002dINF.page.exDocumento.edita_jsp._jspx_meth_c_005fif_005f22(edita_jsp.java:2727)
	at org.apache.jsp.WEB_002dINF.page.exDocumento.edita_jsp.access$22(edita_jsp.java:2712)
	at org.apache.jsp.WEB_002dINF.page.exDocumento.edita_jsp$Helper.invoke0(edita_jsp.java:3201)
	at org.apache.jsp.WEB_002dINF.page.exDocumento.edita_jsp$Helper.invoke(edita_jsp.java:3310)
	at org.apache.jsp.tag.meta.http_003a.localhost.jeetags.pagina_tag.doTag(pagina_tag.java:225)
	at org.apache.jsp.WEB_002dINF.page.exDocumento.edita_jsp._jspx_meth_siga_005fpagina_005f0(edita_jsp.java:170)
	at org.apache.jsp.WEB_002dINF.page.exDocumento.edita_jsp._jspService(edita_jsp.java:104)
	... 82 more
Caused by: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.el.ELException: JBWEB006003: Cannot convert [1, , ] of type class java.lang.String to class java.lang.Long
	at org.apache.taglibs.standard.tag.common.core.ImportSupport.acquireString(ImportSupport.java:357)
	at org.apache.taglibs.standard.tag.common.core.ImportSupport.doEndTag(ImportSupport.java:204)
	at org.apache.jsp.WEB_002dINF.page.exDocumento.edita_jsp._jspx_meth_c_005fimport_005f0(edita_jsp.java:2877)
	at org.apache.jsp.WEB_002dINF.page.exDocumento.edita_jsp._jspx_meth_c_005fif_005f25(edita_jsp.java:2847)
	at org.apache.jsp.WEB_002dINF.page.exDocumento.edita_jsp.access$30(edita_jsp.java:2832)
	at org.apache.jsp.WEB_002dINF.page.exDocumento.edita_jsp$Helper.invoke5(edita_jsp.java:3290)
	at org.apache.jsp.WEB_002dINF.page.exDocumento.edita_jsp$Helper.invoke(edita_jsp.java:3325)
	... 92 more
Caused by: javax.servlet.jsp.JspException: javax.el.ELException: JBWEB006003: Cannot convert [1, , ] of type class java.lang.String to class java.lang.Long
	at org.apache.jsp.paginas.expediente.modelos.formDeclaracaoAjusteAnualIRPF_jsp$Helper.invoke(formDeclaracaoAjusteAnualIRPF_jsp.java:1032)
	at org.apache.jsp.tag.web.mod.entrevista_tag._jspx_meth_c_005fif_005f0(entrevista_tag.java:100)
	at org.apache.jsp.tag.web.mod.entrevista_tag.doTag(entrevista_tag.java:63)
	at org.apache.jsp.paginas.expediente.modelos.formDeclaracaoAjusteAnualIRPF_jsp._jspx_meth_mod_005fentrevista_005f0(formDeclaracaoAjusteAnualIRPF_jsp.java:132)
	at org.apache.jsp.paginas.expediente.modelos.formDeclaracaoAjusteAnualIRPF_jsp.access$0(formDeclaracaoAjusteAnualIRPF_jsp.java:123)
	at org.apache.jsp.paginas.expediente.modelos.formDeclaracaoAjusteAnualIRPF_jsp$Helper.invoke0(formDeclaracaoAjusteAnualIRPF_jsp.java:794)
	at org.apache.jsp.paginas.expediente.modelos.formDeclaracaoAjusteAnualIRPF_jsp$Helper.invoke(formDeclaracaoAjusteAnualIRPF_jsp.java:1006)
	at org.apache.jsp.tag.web.mod.modelo_tag.doTag(modelo_tag.java:206)
	at org.apache.jsp.paginas.expediente.modelos.formDeclaracaoAjusteAnualIRPF_jsp._jspx_meth_mod_005fmodelo_005f0(formDeclaracaoAjusteAnualIRPF_jsp.java:118)
	at org.apache.jsp.paginas.expediente.modelos.formDeclaracaoAjusteAnualIRPF_jsp._jspService(formDeclaracaoAjusteAnualIRPF_jsp.java:94)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:365)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:309)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:242)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:832)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:718)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:655)
	at org.apache.taglibs.standard.tag.common.core.ImportSupport.acquireString(ImportSupport.java:347)
	... 98 more
Caused by: javax.el.ELException: JBWEB006003: Cannot convert [1, , ] of type class java.lang.String to class java.lang.Long
	at org.apache.el.lang.ELSupport.coerceToNumber(ELSupport.java:298)
	at org.apache.el.lang.ELSupport.coerceToNumber(ELSupport.java:278)
	at org.apache.el.lang.ELSupport.equals(ELSupport.java:143)
	at org.apache.el.parser.AstEqual.getValue(AstEqual.java:40)
	at org.apache.el.parser.AstOr.getValue(AstOr.java:43)
	at org.apache.el.parser.AstOr.getValue(AstOr.java:38)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:189)
	at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:898)
	at org.apache.jsp.paginas.expediente.modelos.formDeclaracaoAjusteAnualIRPF_jsp._jspx_meth_c_005fwhen_005f0(formDeclaracaoAjusteAnualIRPF_jsp.java:372)
	at org.apache.jsp.paginas.expediente.modelos.formDeclaracaoAjusteAnualIRPF_jsp._jspx_meth_c_005fchoose_005f0(formDeclaracaoAjusteAnualIRPF_jsp.java:342)
	at org.apache.jsp.paginas.expediente.modelos.formDeclaracaoAjusteAnualIRPF_jsp.access$6(formDeclaracaoAjusteAnualIRPF_jsp.java:329)
	at org.apache.jsp.paginas.expediente.modelos.formDeclaracaoAjusteAnualIRPF_jsp$Helper.invoke1(formDeclaracaoAjusteAnualIRPF_jsp.java:831)
	at org.apache.jsp.paginas.expediente.modelos.formDeclaracaoAjusteAnualIRPF_jsp$Helper.invoke(formDeclaracaoAjusteAnualIRPF_jsp.java:1009)

**Comment by adrigrassi** [comment]
Corrigido com a versão 5.4.4.1
