### ISSUE TITLE
[Siga-Wf] Erro ao prosseguir no fluxo

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#159]
Ao clicar em qualquer botão para prosseguir o fluxo do siga-wf ocorre o seguinte abaixo.

- Como reproduzir:

1.Crie um fluxo conforme descrito em #153 
2. Clique em qualquer caminho possível do fluxo, conforme imagem abaixo

![image](https://cloud.githubusercontent.com/assets/2985140/5962391/be27fcec-a7ca-11e4-952c-86053fd2bdd6.png)

- Erro:

```
no applicable exception handler found
expected '-' in holiday date range: 20/01/2012 # Dia de Sao Sebastiao (Capital) 


org.jbpm.graph.def.DelegationException: no applicable exception handler found
	at org.jbpm.graph.def.GraphElement.raiseException(GraphElement.java:368)
	at org.jbpm.graph.def.GraphElement.executeAction(GraphElement.java:283)
	at org.jbpm.graph.def.GraphElement.executeActions(GraphElement.java:240)
	at org.jbpm.graph.def.GraphElement.fireAndPropagateEvent(GraphElement.java:206)
	at org.jbpm.graph.def.GraphElement.fireEvent(GraphElement.java:188)
	at org.jbpm.taskmgmt.exe.TaskInstance.create(TaskInstance.java:157)
	at org.jbpm.taskmgmt.exe.TaskMgmtInstance.createTaskInstance(TaskMgmtInstance.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:192)
	at org.jbpm.taskmgmt.exe.TaskMgmtInstance_$$_jvst1db_c6.createTaskInstance(TaskMgmtInstance_$$_jvst1db_c6.java)
	at org.jbpm.graph.node.TaskNode.execute(TaskNode.java:162)
	at org.jbpm.graph.def.Node.enter(Node.java:381)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:192)
	at org.jbpm.graph.def.Node_$$_jvst1db_ca.enter(Node_$$_jvst1db_ca.java)
	at org.jbpm.graph.def.Transition.take(Transition.java:162)
	at org.jbpm.graph.def.Node.leave(Node.java:450)
	at org.jbpm.graph.node.TaskNode.leave(TaskNode.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:192)
	at org.jbpm.graph.def.Node_$$_jvst1db_ca.leave(Node_$$_jvst1db_ca.java)
	at org.jbpm.graph.exe.Token.signal(Token.java:210)
	at org.jbpm.graph.exe.Token.signal(Token.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:192)
	at org.jbpm.graph.exe.Token_$$_jvst1db_47.signal(Token_$$_jvst1db_47.java)
	at org.jbpm.taskmgmt.exe.TaskInstance.end(TaskInstance.java:441)
	at br.gov.jfrj.siga.wf.webwork.action.WfTaskAction.executeTask(WfTaskAction.java:573)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.opensymphony.xwork.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:358)
	at com.opensymphony.xwork.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:218)
	at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:192)
	at com.opensymphony.xwork.interceptor.AroundInterceptor.intercept(AroundInterceptor.java:31)
	at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
	at com.opensymphony.xwork.interceptor.AroundInterceptor.intercept(AroundInterceptor.java:31)
	at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
	at com.opensymphony.xwork.interceptor.AroundInterceptor.intercept(AroundInterceptor.java:31)
	at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
	at com.opensymphony.xwork.interceptor.AroundInterceptor.intercept(AroundInterceptor.java:31)
	at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
	at com.opensymphony.xwork.interceptor.AroundInterceptor.intercept(AroundInterceptor.java:31)
	at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
	at com.opensymphony.xwork.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:186)
	at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
	at com.opensymphony.webwork.interceptor.FileUploadInterceptor.intercept(FileUploadInterceptor.java:174)
	at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
	at com.opensymphony.xwork.DefaultActionProxy.execute(DefaultActionProxy.java:116)
	at com.opensymphony.webwork.dispatcher.DispatcherUtils.serviceAction(DispatcherUtils.java:273)
	at com.opensymphony.webwork.dispatcher.FilterDispatcher.doFilter(FilterDispatcher.java:202)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at br.gov.jfrj.siga.wf.util.WfThreadFilter.doFiltro(WfThreadFilter.java:117)
	at br.gov.jfrj.siga.wf.util.WfThreadFilter.executaFiltro(WfThreadFilter.java:110)
	at br.gov.jfrj.siga.wf.util.WfThreadFilter.doFilter(WfThreadFilter.java:60)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
	at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.event(JBossWebContext.java:91)
	at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.invoke(JBossWebContext.java:72)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:499)
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: expected '-' in holiday date range: 20/01/2012 # Dia de Sao Sebastiao (Capital)
	at org.jbpm.calendar.Holiday.(Holiday.java:73)
	at org.jbpm.calendar.Holiday.parseHolidays(Holiday.java:53)
	at org.jbpm.calendar.BusinessCalendar.(BusinessCalendar.java:80)
	at org.jbpm.calendar.BusinessCalendar.(BusinessCalendar.java:71)
	at org.jbpm.scheduler.def.CreateTimerAction.createTimer(CreateTimerAction.java:141)
	at org.jbpm.scheduler.def.CreateTimerAction.execute(CreateTimerAction.java:87)
	at org.jbpm.graph.def.GraphElement.executeActionImpl(GraphElement.java:300)
	at org.jbpm.graph.def.GraphElement.executeAction(GraphElement.java:267)
	... 83 more

```

**Comment by kmacedovarela** [comment]
Devido a uma exceção lançada pelo jbpm no processamento dos feriados o workflow não era gerado. Este erro nao ocorria na versão existente, porém durante a migração do sigawf o jbpm foi atualizado em consequência da atualização para hibernate 4.

fa61feed098be332b3d0a09f1e51f30ec16dea96
