### ISSUE TITLE
Siga-GC: Erro na pesquisa de conhecimentos

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#1842]
Erro na pesquisa utilizando minha matrícula como Autor e mantendo os demais campos com seus valores default.

![erro_pesquisa_GC](https://user-images.githubusercontent.com/4949149/118192946-55b66480-b41d-11eb-9858-f88f03cf8369.png)

**Comment by Chrystinne** [comment]
<html>
<body>
<div class="gt-hd clearfix" style="box-sizing: border-box; margin: 0px; padding: 1px 0px 0px; background: url(&quot;../images/gt/hd-bkg.jpg&quot;) 0px 100% repeat-x; display: block; color: rgb(33, 37, 41); font-family: Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="gt-leaf-watermark clearfix" style="box-sizing: border-box; margin: 0px; padding: 0px; display: block; background: url(&quot;../images/gt/leaves-watermark.png&quot;) 99% 0px no-repeat;"><div class="gt-hd-top clearfix" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 10px; overflow: hidden; border-bottom: 1px solid rgb(59, 39, 22); display: block; height: auto !important;"><div class="gt-fixed-wrap clearfix" style="box-sizing: border-box; margin: 0px; padding: 0px; display: block;"><div class="gt-util-box" style="box-sizing: border-box; margin: 0px 20px 0px 0px; padding: 0px; color: rgb(238, 238, 238); font-size: 12.09px; float: right; display: inline;"><div class="gt-util-box-inner" style="box-sizing: border-box; margin: 0px; padding: 10px 2em 0.35em; font-size: 12.09px;"><p style="box-sizing: border-box; margin: 0px; padding: 0px; line-height: 15.717px; text-align: right;">Olá,<span> </span><strong style="box-sizing: border-box; font-weight: bold; font-style: inherit;">Chrystinne Oliveira Fernandes - COSADM<span> </span></strong><span class="gt-util-separator" style="box-sizing: border-box; padding: 0px 0.35em;">|</span><span> </span><a href="http://localhost:8080/siga/public/app/logout" style="box-sizing: border-box; color: rgb(238, 238, 238); text-decoration: none; background-color: transparent;">sair</a></p><p style="box-sizing: border-box; margin: 0px; padding: 10px 0px 0px; line-height: 15.717px; text-align: right;"></p></div></div><a href="http://localhost:8080/siga" title="Página inicial" class="link-sem-estilo" style="box-sizing: border-box; color: rgb(54, 91, 109); text-decoration: none; background-color: transparent;"><div class="gt-logo" style="box-sizing: border-box; margin: 0px 0px 0px 35px; padding: 0px; color: rgb(255, 255, 255); font-size: 27.95px; font-weight: normal; float: left; display: inline;"><img src="http://localhost:8080/siga/imagens/logo.png" style="box-sizing: border-box; vertical-align: middle; border: 0px; margin-top: 3px; margin-bottom: -13px;"></div><div class="gt-company" style="box-sizing: border-box; margin: 0px 0px 0px 35px; padding: 10px 0px 0px 35px; color: rgb(255, 255, 255); font-size: 13px; font-weight: bold; display: block;"><strong style="box-sizing: border-box; font-weight: bold; font-style: inherit;">- Tribunal Regional Federal - 2ª Região</strong></div><div class="gt-version" style="box-sizing: border-box; margin: 0px 0px 0px 35px; padding: 10px 0px 0px; color: rgb(255, 255, 255); font-size: 13px; font-weight: normal; display: block;">Sistema Integrado de Gestão Administrativa</div></a></div></div></div></div><div id="quadroAviso" style="box-sizing: border-box; margin: 0px; padding: 4px; font-family: Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; position: absolute; font-weight: bold; color: white; visibility: hidden;"></div><div class="gt-bd clearfix" style="box-sizing: border-box; margin: 0px; padding: 25px 35px; display: block; color: rgb(33, 37, 41); font-family: Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="gt-content clearfix" style="box-sizing: border-box; margin: 0px; padding: 0px; display: block;"><div id="caption" class="" style="box-sizing: border-box; margin: 0px; padding: 0px;"><h2 style="box-sizing: border-box; margin: 0px 0px 10px; font-family: inherit; font-weight: bold; line-height: 1.2; color: rgb(14, 32, 41); font-size: 21.008px; padding: 0px;">Não Foi Possível Completar a Operação (localhost)</h2></div><div class="gt-content-box" style="box-sizing: border-box; margin: 0px; padding: 1px; border-radius: 5px; background-color: rgb(255, 255, 255); border: 1px solid rgb(204, 204, 204);">

javax.servlet.ServletException: br.com.caelum.vraptor.InterceptionException: br.com.caelum.vraptor.InterceptionException: java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: nullorder near line 1, column 109 [from br.gov.jfrj.siga.gc.model.GcInformacao inf where inf.hisDtIni is not null and inf.autor.idPessoaIni = nullorder by inf.hisDtIni desc]br.com.caelum.vraptor.InterceptionException: br.com.caelum.vraptor.InterceptionException: java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: nullorder near line 1, column 109 [from br.gov.jfrj.siga.gc.model.GcInformacao inf where inf.hisDtIni is not null and inf.autor.idPessoaIni = nullorder by inf.hisDtIni desc] | javax.servlet.ServletException: br.com.caelum.vraptor.InterceptionException: br.com.caelum.vraptor.InterceptionException: java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: nullorder near line 1, column 109 [from br.gov.jfrj.siga.gc.model.GcInformacao inf where inf.hisDtIni is not null and inf.autor.idPessoaIni = nullorder by inf.hisDtIni desc] | br.com.caelum.vraptor.InterceptionException: br.com.caelum.vraptor.InterceptionException: java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: nullorder near line 1, column 109 [from br.gov.jfrj.siga.gc.model.GcInformacao inf where inf.hisDtIni is not null and inf.autor.idPessoaIni = nullorder by inf.hisDtIni desc]
-- | -- | --
javax.servlet.ServletException: br.com.caelum.vraptor.InterceptionException: br.com.caelum.vraptor.InterceptionException: java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: nullorder near line 1, column 109 [from br.gov.jfrj.siga.gc.model.GcInformacao inf where inf.hisDtIni is not null and inf.autor.idPessoaIni = nullorder by inf.hisDtIni desc]
br.com.caelum.vraptor.InterceptionException: br.com.caelum.vraptor.InterceptionException: java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: nullorder near line 1, column 109 [from br.gov.jfrj.siga.gc.model.GcInformacao inf where inf.hisDtIni is not null and inf.autor.idPessoaIni = nullorder by inf.hisDtIni desc]
java.lang.RuntimeException: javax.servlet.ServletException: br.com.caelum.vraptor.InterceptionException: br.com.caelum.vraptor.InterceptionException: java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: nullorder near line 1, column 109 [from br.gov.jfrj.siga.gc.model.GcInformacao inf where inf.hisDtIni is not null  and inf.autor.idPessoaIni = nullorder by inf.hisDtIni desc] 	at br.gov.jfrj.siga.idp.jwt.AuthJwtFormFilter.doFilter(AuthJwtFormFilter.java:164) 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) 	at io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:55) 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) 	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) 	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) 	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132) 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) 	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50) 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) 	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) 	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292) 	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81) 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138) 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135) 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) 	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504) 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272) 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81) 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104) 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376) 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830) 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985) 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487) 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378) 	at java.lang.Thread.run(Thread.java:748) Caused by: javax.servlet.ServletException: br.com.caelum.vraptor.InterceptionException: br.com.caelum.vraptor.InterceptionException: java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: nullorder near line 1, column 109 [from br.gov.jfrj.siga.gc.model.GcInformacao inf where inf.hisDtIni is not null  and inf.autor.idPessoaIni = nullorder by inf.hisDtIni desc] 	at br.gov.jfrj.siga.gc.util.GcThreadFilter.doFilter(GcThreadFilter.java:47) 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) 	at br.gov.jfrj.siga.base.log.RequestLoggerFilter.doFilter(RequestLoggerFilter.java:29) 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) 	at br.gov.jfrj.siga.idp.jwt.AuthJwtFormFilter.doFilter(AuthJwtFormFilter.java:137) 	... 47 more Caused by: br.com.caelum.vraptor.InterceptionException: br.com.caelum.vraptor.InterceptionException: java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: nullorder near line 1, column 109 [from br.gov.jfrj.siga.gc.model.GcInformacao inf where inf.hisDtIni is not null  and inf.autor.idPessoaIni = nullorder by inf.hisDtIni desc] 	at br.com.caelum.vraptor.interceptor.StepInvoker.invokeMethod(StepInvoker.java:69) 	at br.com.caelum.vraptor.interceptor.StepInvoker.tryToInvoke(StepInvoker.java:55) 	at br.com.caelum.vraptor.interceptor.StepInvoker$Proxy$_$_WeldClientProxy.tryToInvoke(Unknown Source) 	at br.com.caelum.vraptor.interceptor.InterceptorExecutor.executeAround(InterceptorExecutor.java:75) 	at br.com.caelum.vraptor.interceptor.InterceptorExecutor$Proxy$_$_WeldClientProxy.executeAround(Unknown Source) 	at br.com.caelum.vraptor.interceptor.AspectStyleInterceptorHandler.execute(AspectStyleInterceptorHandler.java:85) 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83) 	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:63) 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83) 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.start(DefaultInterceptorStack.java:93) 	at br.com.caelum.vraptor.core.DefaultInterceptorStack$Proxy$_$_WeldClientProxy.start(Unknown Source) 	at br.com.caelum.vraptor.observer.RequestHandlerObserver.handle(RequestHandlerObserver.java:93) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95) 	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85) 	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:129) 	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330) 	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308) 	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286) 	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124) 	at org.jboss.weld.util.Observers.notify(Observers.java:166) 	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285) 	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273) 	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96) 	at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:123) 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) 	at br.gov.jfrj.siga.gc.util.GcThreadFilter.doFilter(GcThreadFilter.java:44) 	... 53 more Caused by: br.com.caelum.vraptor.InterceptionException: java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: nullorder near line 1, column 109 [from br.gov.jfrj.siga.gc.model.GcInformacao inf where inf.hisDtIni is not null  and inf.autor.idPessoaIni = nullorder by inf.hisDtIni desc] 	at br.com.caelum.vraptor.interceptor.StepInvoker.invokeMethod(StepInvoker.java:69) 	at br.com.caelum.vraptor.interceptor.StepInvoker.tryToInvoke(StepInvoker.java:55) 	at br.com.caelum.vraptor.interceptor.StepInvoker$Proxy$_$_WeldClientProxy.tryToInvoke(Unknown Source) 	at br.com.caelum.vraptor.interceptor.InterceptorExecutor.executeAround(InterceptorExecutor.java:75) 	at br.com.caelum.vraptor.interceptor.InterceptorExecutor$Proxy$_$_WeldClientProxy.executeAround(Unknown Source) 	at br.com.caelum.vraptor.interceptor.AspectStyleInterceptorHandler.execute(AspectStyleInterceptorHandler.java:85) 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83) 	at br.com.caelum.vraptor.interceptor.ExceptionHandlerInterceptor.intercept(ExceptionHandlerInterceptor.java:75) 	at br.com.caelum.vraptor.interceptor.ExceptionHandlerInterceptor$Proxy$_$_WeldClientProxy.intercept(Unknown Source) 	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler$1.call(ToInstantiateInterceptorHandler.java:71) 	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler$1.call(ToInstantiateInterceptorHandler.java:68) 	at br.com.caelum.vraptor.core.Try.run(Try.java:18) 	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.executeSafely(ToInstantiateInterceptorHandler.java:68) 	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:61) 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83) 	at br.com.caelum.vraptor.interceptor.FlashInterceptor.intercept(FlashInterceptor.java:98) 	at br.com.caelum.vraptor.interceptor.FlashInterceptor$Proxy$_$_WeldClientProxy.intercept(Unknown Source) 	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler$1.call(ToInstantiateInterceptorHandler.java:71) 	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler$1.call(ToInstantiateInterceptorHandler.java:68) 	at br.com.caelum.vraptor.core.Try.run(Try.java:18) 	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.executeSafely(ToInstantiateInterceptorHandler.java:68) 	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:61) 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83) 	at br.com.caelum.vraptor.core.DefaultInterceptorStack$Proxy$_$_WeldClientProxy.next(Unknown Source) 	at br.com.caelum.vraptor.interceptor.DefaultSimpleInterceptorStack.next(DefaultSimpleInterceptorStack.java:49) 	at br.com.caelum.vraptor.interceptor.DefaultSimpleInterceptorStack$Proxy$_$_WeldClientProxy.next(Unknown Source) 	at br.gov.jfrj.siga.gc.vraptor.GcInterceptor.intercept(GcInterceptor.java:53) 	at br.gov.jfrj.siga.gc.vraptor.GcInterceptor$Proxy$_$_WeldClientProxy.intercept(Unknown Source) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at net.vidageek.mirror.provider.java.PureJavaMethodReflectionProvider.invoke(PureJavaMethodReflectionProvider.java:38) 	at net.vidageek.mirror.invoke.MethodHandlerByMethod.withArgs(MethodHandlerByMethod.java:54) 	at br.com.caelum.vraptor.core.DefaultReflectionProvider.invoke(DefaultReflectionProvider.java:42) 	at br.com.caelum.vraptor.core.DefaultReflectionProvider$Proxy$_$_WeldClientProxy.invoke(Unknown Source) 	at br.com.caelum.vraptor.interceptor.StepInvoker.invokeMethod(StepInvoker.java:64) 	... 83 more Caused by: java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: nullorder near line 1, column 109 [from br.gov.jfrj.siga.gc.model.GcInformacao inf where inf.hisDtIni is not null  and inf.autor.idPessoaIni = nullorder by inf.hisDtIni desc] 	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:138) 	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181) 	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188) 	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:729) 	at org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:23) 	at sun.reflect.GeneratedMethodAccessor223.invoke(Unknown Source) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) 	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) 	at org.jboss.weldx.persistence.EntityManager$365791516$Proxy$_$_WeldClientProxy.createQuery(Unknown Source) 	at br.gov.jfrj.siga.gc.util.GcInformacaoFiltro.buscar(GcInformacaoFiltro.java:172) 	at br.gov.jfrj.siga.gc.vraptor.AppController.listar(AppController.java:532) 	at br.gov.jfrj.siga.gc.vraptor.AppController$Proxy$_$_WeldSubclass.listar(Unknown Source) 	at br.gov.jfrj.siga.gc.vraptor.AppController$Proxy$_$_WeldClientProxy.listar(Unknown Source) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at net.vidageek.mirror.provider.java.PureJavaMethodReflectionProvider.invoke(PureJavaMethodReflectionProvider.java:38) 	at net.vidageek.mirror.invoke.MethodHandlerByMethod.withArgs(MethodHandlerByMethod.java:54) 	at br.com.caelum.vraptor.core.DefaultReflectionProvider.invoke(DefaultReflectionProvider.java:42) 	at br.com.caelum.vraptor.core.DefaultReflectionProvider$Proxy$_$_WeldClientProxy.invoke(Unknown Source) 	at br.com.caelum.vraptor.observer.ExecuteMethod$1.call(ExecuteMethod.java:82) 	at br.com.caelum.vraptor.observer.ExecuteMethod$1.call(ExecuteMethod.java:72) 	at br.com.caelum.vraptor.core.Try.run(Try.java:18) 	at br.com.caelum.vraptor.observer.ExecuteMethod.execute(ExecuteMethod.java:72) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95) 	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85) 	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:129) 	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330) 	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308) 	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286) 	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124) 	at org.jboss.weld.util.Observers.notify(Observers.java:166) 	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285) 	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273) 	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96) 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:78) 	at br.com.caelum.vraptor.core.DefaultInterceptorStack$Proxy$_$_WeldClientProxy.next(Unknown Source) 	at br.com.caelum.vraptor.interceptor.DefaultSimpleInterceptorStack.next(DefaultSimpleInterceptorStack.java:49) 	at br.com.caelum.vraptor.interceptor.DefaultSimpleInterceptorStack$Proxy$_$_WeldClientProxy.next(Unknown Source) 	at br.com.caelum.vraptor.jpa.JPATransactionInterceptor.intercept(JPATransactionInterceptor.java:73) 	at br.com.caelum.vraptor.jpa.JPATransactionInterceptor$Proxy$_$_WeldClientProxy.intercept(Unknown Source) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at net.vidageek.mirror.provider.java.PureJavaMethodReflectionProvider.invoke(PureJavaMethodReflectionProvider.java:38) 	at net.vidageek.mirror.invoke.MethodHandlerByMethod.withArgs(MethodHandlerByMethod.java:54) 	at br.com.caelum.vraptor.core.DefaultReflectionProvider.invoke(DefaultReflectionProvider.java:42) 	at br.com.caelum.vraptor.core.DefaultReflectionProvider$Proxy$_$_WeldClientProxy.invoke(Unknown Source) 	at br.com.caelum.vraptor.interceptor.StepInvoker.invokeMethod(StepInvoker.java:64) 	... 119 more Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: nullorder near line 1, column 109 [from br.gov.jfrj.siga.gc.model.GcInformacao inf where inf.hisDtIni is not null  and inf.autor.idPessoaIni = nullorder by inf.hisDtIni desc] 	at org.hibernate.hql.internal.ast.QuerySyntaxException.convert(QuerySyntaxException.java:74) 	at org.hibernate.hql.internal.ast.ErrorTracker.throwQueryException(ErrorTracker.java:93) 	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.parse(QueryTranslatorImpl.java:296) 	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:188) 	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:143) 	at org.hibernate.engine.query.spi.HQLQueryPlan.(HQLQueryPlan.java:119) 	at org.hibernate.engine.query.spi.HQLQueryPlan.(HQLQueryPlan.java:80) 	at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:153) 	at org.hibernate.internal.AbstractSharedSessionContract.getQueryPlan(AbstractSharedSessionContract.java:611) 	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:720) 	... 172 more

</div></div></div>
</body>
</html>
