### ISSUE TITLE
Erro em todas as aplicações Play.

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#187]
10:13:20,710 ERROR [stderr] (http-/10.10.0.72:8280-1) java.lang.NullPointerException
10:13:20,711 ERROR [stderr] (http-/10.10.0.72:8280-1)   at br.gov.jfrj.siga.base.SigaHTTP.getIdp(SigaHTTP.java:211)
10:13:20,711 ERROR [stderr] (http-/10.10.0.72:8280-1)   at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:89)
10:13:20,712 ERROR [stderr] (http-/10.10.0.72:8280-1)   at br.gov.jfrj.siga.base.SigaHTTP.get(SigaHTTP.java:79)
10:13:20,712 ERROR [stderr] (http-/10.10.0.72:8280-1)   at controllers.SigaApplication.obterCabecalhoEUsuario(SigaApplication.java:65)
10:13:20,712 ERROR [stderr] (http-/10.10.0.72:8280-1)   at controllers.Application.addDefaults(Application.java:80)

**Comment by kmacedovarela** [comment]
O erro ocorre quando o usuário está "substituindo" alguém. @hodrigohamalho

**Comment by kmacedovarela** [comment]
Quando chamado por uma aplicação play, não estava sendo identificada a named query configurada via arquivo hbm.xml

Foi configurado então também a named query via annotation na classe DpSubstituicao.java

7510d1a
