### ISSUE TITLE
PCRJ_754 - erro na consulta de validação de documentos - java.lang.NullPointerException

### ISSUE THREAD

**Issue by ivangsilverio** [projeto-siga/siga#1885]
Para similar o erro:

1) acessar o sistema;
2) informar o número XXX-XXX-2020/00001 na caixa de pesquisa da diagonal superior direita;
3) clicar na função dossiê;
4) obter a url de validação no rodapé do documento, basta clicar.
5) validar o recapch

erro de java.lang.NullPointerException na consulta externa

testes feitos nas versões 10.0.17 e 9.0.22.3

https://XXXXXX/sigaex/public/app/autenticar?n=XXX-XXXX , 

e informar o número

recebemos

java.lang.NullPointerException
at br.gov.jfrj.siga.ex.vo.ExMovimentacaoVO.addAcoes(ExMovimentacaoVO.java:255)
at br.gov.jfrj.siga.ex.vo.ExMovimentacaoVO.(ExMovimentacaoVO.java:165)
at br.gov.jfrj.siga.ex.vo.ExMobilVO.(ExMobilVO.java:187)
at br.gov.jfrj.siga.ex.vo.ExMobilVO.(ExMobilVO.java:106)
at br.gov.jfrj.siga.ex.vo.ExDocumentoVO.(ExDocumentoVO.java:259)
at br.gov.jfrj.siga.vraptor.ExAutenticacaoController.arquivoAutenticado(ExAutenticacaoController.java:325)
at br.gov.jfrj.siga.vraptor.ExAutenticacaoController_$$jvstf9f_2f.arquivoAutenticado(ExAutenticacaoController$$_jvstf9f_2f.java)
at br.gov.jfrj.siga.vraptor.ExAutenticacaoController.autenticar(ExAutenticacaoController.java:179)
at br.gov.jfrj.siga.vraptor.AccessAuthInterceptor.intercept(AccessAuthInterceptor.java:53)
at br.gov.jfrj.siga.vraptor.SigaInterceptor.intercept(SigaInterceptor.java:34)
at br.gov.jfrj.siga.vraptor.AplicacaoExceptionInterceptor.intercept(AplicacaoExceptionInterceptor.java:47)
at br.gov.jfrj.siga.util.ExInterceptor.intercept(ExInterceptor.java:76)
at br.gov.jfrj.siga.vraptor.SigaTransacionalInterceptor.intercept(SigaTransacionalInterceptor.java:83)

**Comment by ivangsilverio** [comment]
Corrigido na versão 10.0.18
