### ISSUE TITLE
PCRJ_781 - Erro ao tentar alterar permissões dos perfis de acesso v10.0.18

### ISSUE THREAD

**Issue by ivangsilverio** [projeto-siga/siga#1895]
versão: 10.0.18

para simular o erro:
1) menu/ gestão de identidade / configurar permissões
2) escolher perfil

erro:

java.lang.IllegalArgumentException: Unable to locate persister: br.gov.jfrj.siga.cp.model.enm.CpTipoDeConfiguracao
at br.gov.jfrj.siga.model.dao.ModeloDao.consultar(ModeloDao.java:92)
at br.gov.jfrj.siga.vraptor.GrupoController.prepare(GrupoController.java:732)
at br.gov.jfrj.siga.vraptor.PerfilController.(PerfilController.java:54)
at br.gov.jfrj.siga.vraptor.AccessAuthInterceptor.intercept(AccessAuthInterceptor.java:53)
at br.gov.jfrj.siga.vraptor.SigaTransacionalInterceptor.intercept(SigaTransacionalInterceptor.java:83)
at br.gov.jfrj.siga.util.GiInterceptor.intercept(GiInterceptor.java:62)
at br.gov.jfrj.siga.vraptor.SigaInterceptor.intercept(SigaInterceptor.java:34)
at br.gov.jfrj.siga.vraptor.AplicacaoExceptionInterceptor.intercept(AplicacaoExceptionInterceptor.java:47)
Caused by: org.hibernate.UnknownEntityTypeException: Unable to locate persister: br.gov.jfrj.siga.cp.model.enm.CpTipoDeConfiguracao

**Comment by ivangsilverio** [comment]
![erroPerfil](https://user-images.githubusercontent.com/8059257/125084974-778c3a80-e0a0-11eb-9e75-262947759ca9.png)
