### ISSUE TITLE
EX: Erro ao visualizar documentos Capturados(v10.0.17)

### ISSUE THREAD

**Issue by jmolivei** [projeto-siga/siga#1897]
java.lang.RuntimeException: erro na geração do documento.
	at br.gov.jfrj.siga.vraptor.ExArquivoController.aExibir(ExArquivoController.java:257)
	at br.gov.jfrj.siga.vraptor.AccessAuthInterceptor.intercept(AccessAuthInterceptor.java:53)
	at br.gov.jfrj.siga.vraptor.SigaInterceptor.intercept(SigaInterceptor.java:34)
	at br.gov.jfrj.siga.vraptor.AplicacaoExceptionInterceptor.intercept(AplicacaoExceptionInterceptor.java:47)
	at br.gov.jfrj.siga.util.ExInterceptor.intercept(ExInterceptor.java:76)
	at br.gov.jfrj.siga.vraptor.SigaTransacionalInterceptor.intercept(SigaTransacionalInterceptor.java:83)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at br.gov.jfrj.siga.vraptor.ExArquivoController.aExibir(ExArquivoController.java:184)
Caused by: java.lang.NullPointerException

![image](https://user-images.githubusercontent.com/5268745/125332677-b7148a00-e31f-11eb-8748-4a357797dbe3.png)

**Comment by jmolivei** [comment]
Cenário após implementação da correção

![image](https://user-images.githubusercontent.com/5268745/125353975-9e18d280-e339-11eb-8ae5-f54d4ac55bc0.png)

**Comment by jmolivei** [comment]
Resolvido pelo commit 9ec3e2f
