### ISSUE TITLE
PCRJ_1161 - erros ao receber documentos apensados

### ISSUE THREAD

**Issue by ivangsilverio** [projeto-siga/siga#1973]
Dois processos criados e apensados na versão 10.0.21.8

Documento mestre: IPL-PRO-2021/00036
Documento filho: IPL-PRO-2021/00037

Problema 1) 
Ao tramitar o documento, na caixa de entrada digital aparecem a numeração de dois processos (mestre e filho). Usuário não tem como saber qual é o documento mestre para receber, pois não há nenhuma indicação. Necessário que o sistema exiba somente o documento mestre na caixa de entrada digital ou que haja alguma indicação de quem é o documento mestre para ser recebido. 

Este problema também acontece na - v.9.0.22.3.

Problema 2) Não é possível receber o documento mestre, apresentando erro java. 

Problema 3) Se o usuário clicar no documento filho, somente o filho será recebido, e o mestre continuará preso na caixa de entrada digital, apresentando erro java, na tentativa do seu recebimento. 

Erro: 

java.lang.RuntimeException: Erro ao receber documento.
	at br.gov.jfrj.siga.ex.bl.ExBL.receber(ExBL.java:4578)
	at br.gov.jfrj.siga.vraptor.ExDocumentoController.exibe(ExDocumentoController.java:1385)
	at br.gov.jfrj.siga.vraptor.AccessAuthInterceptor.intercept(AccessAuthInterceptor.java:53)
	at br.gov.jfrj.siga.vraptor.SigaInterceptor.intercept(SigaInterceptor.java:34)
	at br.gov.jfrj.siga.vraptor.AplicacaoExceptionInterceptor.intercept(AplicacaoExceptionInterceptor.java:47)
	at br.gov.jfrj.siga.util.ExInterceptor.intercept(ExInterceptor.java:76)
	at br.gov.jfrj.siga.vraptor.SigaTransacionalInterceptor.intercept(SigaTransacionalInterceptor.java:83)
Caused by: br.gov.jfrj.siga.base.AplicacaoException: Não foi encontrado nenhum trâmite pendente para o usuário corrente ou sua lotação
	at br.gov.jfrj.siga.ex.bl.ExBL.receber(ExBL.java:4546)

**Comment by ivangsilverio** [comment]
Em reunião técnica comentamos que o melhor comportamento seria exibir apenas o documento principal.
