### ISSUE TITLE
PCRJ_1322 - Erro ao abrir um volume.

### ISSUE THREAD

**Issue by ivangsilverio** [projeto-siga/siga#1997]
Versão SIGA 10.0.21.9

Observemos o seguinte cenário A:
 
Eu, usuário João, do órgão ZONA SUL, da lotação IPANEMA, cadastro  um documento, tramito para um outro atendente, Maria , do órgão ZONA SUL, da lotação COPACANA..
 
 
Maria  cria vários documentos e preenche o número de páginas do volume corrente. Este é fechado automáticamente. Ao tentar incluir novo volume o sistema resposta da seguinte forma (janela de erro vermelha):
 

 
 
java.lang.RuntimeException: Erro ao criar novo volume.
at br.gov.jfrj.siga.ex.bl.ExBL.criarVolume(ExBL.java:3192)
at br.gov.jfrj.siga.vraptor.ExDocumentoController.criarVolume(ExDocumentoController.java:449)
at br.gov.jfrj.siga.vraptor.AccessAuthInterceptor.intercept(AccessAuthInterceptor.java:53)
at br.gov.jfrj.siga.vraptor.SigaInterceptor.intercept(SigaInterceptor.java:34)
at br.gov.jfrj.siga.vraptor.AplicacaoExceptionInterceptor.intercept(AplicacaoExceptionInterceptor.java:47)
at br.gov.jfrj.siga.util.ExInterceptor.intercept(ExInterceptor.java:76)
at br.gov.jfrj.siga.vraptor.SigaTransacionalInterceptor.intercept(SigaTransacionalInterceptor.java:83)
Caused by: br.gov.jfrj.siga.base.AplicacaoException: não é possível apensar a um documento que esteja em outra lotação
at br.gov.jfrj.siga.ex.bl.ExBL.apensarDocumento(ExBL.java:6420)
at br.gov.jfrj.siga.ex.bl.ExBL.criarVolume(ExBL.java:3188)
 
 
Observemos o seguinte cenário B:
 
Eu, usuário João, da lotação IPANEMA, cadastrante do um documento, tramito o  processo para um outro atendente, José , da lotação IPANEMA..
 
José  cria vários documentos e preenche o número de páginas do volume corrente. Este é fechado automáticamente. Ao tentar incluir novo volume o sistema abre corretamente.
 
Observemos o seguinte cenário C:
 
Eu, usuário João, da lotação IPANEMA, cadastrante do um documento, crio vários documentos e preencho o número de páginas máxima do volume corrente. Este é fechado automáticamente. Ao tentar incluir novo volume o sistema abre corretamente.
 
Peço orientação sobre o melhor comportamento do cenário A.

**Comment by ivangsilverio** [comment]
também tratado em 
https://colabore.trf2.jus.br/mod/forum/discuss.php?d=141

**Comment by ivangsilverio** [comment]
Prezadxs,

este erro não ocorre na versão  10.1.0.1, mas na 10.0.27.8 sim. É possível realizar um cherry pick para as versões anteriores?

tentamos com este commit, sem sucesso.
( 5c1ea3525f34c8ac2c28dd730a2ee984b3cc5f4c )

Dinâmica do erro:
acessar o documento, versões  v.10.0.21.x, e  v.10.0.27.8
1) Locar como o atendente do documento
2) pesquisar o documento,
3) clicar em abrir novo volume

resultado:
java.lang.RuntimeException: Erro ao criar novo volume.
at br.gov.jfrj.siga.ex.bl.ExBL.criarVolume(ExBL.java:3192)
at br.gov.jfrj.siga.vraptor.ExDocumentoController.criarVolume(ExDocumentoController.java:449)
at br.gov.jfrj.siga.vraptor.AccessAuthInterceptor.intercept(AccessAuthInterceptor.java:53)
at br.gov.jfrj.siga.vraptor.SigaInterceptor.intercept(SigaInterceptor.java:34)
at br.gov.jfrj.siga.vraptor.AplicacaoExceptionInterceptor.intercept(AplicacaoExceptionInterceptor.java:47)
at br.gov.jfrj.siga.util.ExInterceptor.intercept(ExInterceptor.java:76)
at br.gov.jfrj.siga.vraptor.SigaTransacionalInterceptor.intercept(SigaTransacionalInterceptor.java:83)
Caused by: br.gov.jfrj.siga.base.AplicacaoException: A apensação do documento não ser realizada porque ele estáem transito, em transito externo, cancelado ou em local diferente da lotação em que se encontra o documento ao qual se quer apensar
at br.gov.jfrj.siga.ex.bl.ExBL.apensarDocumento(ExBL.java:6415)
at br.gov.jfrj.siga.ex.bl.ExBL.criarVolume(ExBL.java:3188)

**Comment by ivangsilverio** [comment]
Na versão v.10.0.27.8, com o cadastro de configuração pode, para apenso, o erro não ocorre
