### ISSUE TITLE
Stackoverflow

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#213]
Acredito que essa pode ser uma das causas do alto consumo de CPU. @hodrigohamalho, favor verificar. Vi o erro no log, porém não sei como reproduzir.

Ex de log; Acce**, Dia 05/03/2015, 10:00:17,525 ERROR 

````
Caused by: java.lang.StackOverflowError
        at java.lang.Exception.<init>(Exception.java:66) [rt.jar:1.7.0_71]
        at java.io.IOException.<init>(IOException.java:58) [rt.jar:1.7.0_71]
        at java.io.InterruptedIOException.<init>(InterruptedIOException.java:64) [rt.jar:1.7.0_71]
        at java.net.SocketTimeoutException.<init>(SocketTimeoutException.java:43) [rt.jar:1.7.0_71]
        at java.net.SocketInputStream.socketRead0(Native Method) [rt.jar:1.7.0_71]
        at java.net.SocketInputStream.read(SocketInputStream.java:152) [rt.jar:1.7.0_71]
        at java.net.SocketInputStream.read(SocketInputStream.java:122) [rt.jar:1.7.0_71]
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136) [httpcore-4.3.2.jar:4.3.2]
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152) [httpcore-4.3.2.jar:4.3.2]
        at org.apache.http.impl.BHttpConnectionBase.fillInputBuffer(BHttpConnectionBase.java:336) [httpcore-4.3.2.jar:4.3.2]
        at org.apache.http.impl.BHttpConnectionBase.isStale(BHttpConnectionBase.java:355) [httpcore-4.3.2.jar:4.3.2]
        at org.apache.http.impl.conn.CPoolProxy.isStale(CPoolProxy.java:110) [httpclient-4.3.4.jar:4.3.4]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:191) [httpclient-4.3.4.jar:4.3.4]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195) [httpclient-4.3.4.jar:4.3.4]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86) [httpclient-4.3.4.jar:4.3.4]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108) [httpclient-4.3.4.jar:4.3.4]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) [httpclient-4.3.4.jar:4.3.4]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) [httpclient-4.3.4.jar:4.3.4]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57) [httpclient-4.3.4.jar:4.3.4]
        at org.apache.http.client.fluent.Executor.execute(Executor.java:206) [fluent-hc-4.3.4.jar:4.3.4]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:125) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.tryAgain(SigaHTTP.java:156) [siga-base-1.1.jar:]
        at br.gov.jfrj.siga.base.SigaHTTP.handleAuthentication(SigaHTTP.java:147) [siga-base-1.1.jar:]
````

**Comment by hodrigohamalho** [comment]
Creio que o contador não ta sendo atualizado ou está sendo atualizado incorretamente no método TryAgain... dai ta entrando loop infinito. (Até estourar a stack)

**Comment by hodrigohamalho** [comment]
Corrigido em: d26a7928ce95f3a867e1fbdd8df98f16f474263c
