### ISSUE TITLE
CP- Erro ao obter cargoatual no método obterAtual

### ISSUE THREAD

**Issue by jmolivei** [projeto-siga/siga#2455]
Caused by: org.hibernate.QueryException: could not resolve property: hisIdIni of: br.gov.jfrj.siga.dp.DpCargo
	at org.hibernate.persister.entity.AbstractPropertyMapping.propertyException(AbstractPropertyMapping.java:73)
	at org.hibernate.persister.entity.AbstractPropertyMapping.toType(AbstractPropertyMapping.java:67)
	at org.hibernate.persister.entity.AbstractEntityPersister.toType(AbstractEntityPersister.java:1987)
	at org.hibernate.hql.internal.ast.tree.FromElementType.getPropertyType(FromElementType.java:396)
	at org.hibernate.hql.internal.ast.tree.FromElement.getPropertyType(FromElement.java:515)
	at org.hibernate.hql.internal.ast.tree.DotNode.getDataType(DotNode.java:682)
	at org.hibernate.hql.internal.ast.tree.DotNode.prepareLhs(DotNode.java:265)
	at org.hibernate.hql.internal.ast.tree.DotNode.resolve(DotNode.java:205)
	at org.hibernate.hql.internal.ast.HqlSqlWalker.resolve(HqlSqlWalker.java:1045)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.expr(HqlSqlBaseWalker.java:1290)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.exprOrSubquery(HqlSqlBaseWalker.java:4706)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.comparisonExpr(HqlSqlBaseWalker.java:4174)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.logicalExpr(HqlSqlBaseWalker.java:2138)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.logicalExpr(HqlSqlBaseWalker.java:2066)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.whereClause(HqlSqlBaseWalker.java:815)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.query(HqlSqlBaseWalker.java:609)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.selectStatement(HqlSqlBaseWalker.java:313)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.statement(HqlSqlBaseWalker.java:261)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.analyze(QueryTranslatorImpl.java:271)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:191)
	... 237 more

**Comment by jmolivei** [comment]
Solução . Pegar o cargo atual pelo metodo ja implementado na classe DpCargo.
