### ISSUE TITLE
Erro na inicialização do JBoss, ambiente de desenvolvimento

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#264]
@hodrigohamalho e @kmacedovarela , vocês sabem dizer o que pode estar causando isso?

Estou sem poder trabalhar...

12:30:56,318 INFO  [org.jboss.modules] (main) JBoss Modules version 1.3.3.Final-redhat-1
12:30:57,386 INFO  [org.jboss.msc] (main) JBoss MSC version 1.0.4.GA-redhat-1
12:30:57,521 INFO  [org.jboss.as] (MSC service thread 1-6) JBAS015899: JBoss EAP 6.2.3.GA (AS 7.3.3.Final-redhat-3) starting
12:30:58,598 WARN  [org.jboss.modules] (Controller Boot Thread) Failed to define class org.jboss.as.controller.OperationContext$RollbackHandler$2 in Module "org.jboss.as.controller:main" from local module loader @57e603e6 (finder: local module finder @3e0a1e1f (roots: /Users/nato/Development/jboss-eap-6.2.3/modules,/Users/nato/Development/jboss-eap-6.2.3/modules/system/layers/base/.overlays/layer-base-jboss-eap-6.2.3.CP,/Users/nato/Development/jboss-eap-6.2.3/modules/system/layers/base)): java.lang.ClassFormatError: Unknown constant tag 97 in class file org/jboss/as/controller/OperationContext$RollbackHandler$2
	at java.lang.ClassLoader.defineClass1(Native Method) [rt.jar:1.7.0_51]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) [rt.jar:1.7.0_51]
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:361) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:482) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:277) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:92) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.Module.loadModuleClass(Module.java:568) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.as.controller.OperationContext$RollbackHandler.<clinit>(OperationContext.java:899) [jboss-as-controller-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.controller.AbstractOperationContext.completeStep(AbstractOperationContext.java:300) [jboss-as-controller-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.server.operations.SystemPropertyAddHandler.execute(SystemPropertyAddHandler.java:114) [jboss-as-server-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:601) [jboss-as-controller-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.controller.AbstractOperationContext.doCompleteStep(AbstractOperationContext.java:479) [jboss-as-controller-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.controller.AbstractOperationContext.completeStepInternal(AbstractOperationContext.java:283) [jboss-as-controller-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:278) [jboss-as-controller-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:288) [jboss-as-controller-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:291) [jboss-as-controller-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.server.ServerService.boot(ServerService.java:349) [jboss-as-server-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.server.ServerService.boot(ServerService.java:324) [jboss-as-server-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:253) [jboss-as-controller-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at java.lang.Thread.run(Thread.java:744) [rt.jar:1.7.0_51]

12:30:58,604 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) JBAS014612: Operation ("add") failed - address: ([("system-property" => "idp.url")]): java.lang.ClassFormatError: Unknown constant tag 97 in class file org/jboss/as/controller/OperationContext$RollbackHandler$2
	at java.lang.ClassLoader.defineClass1(Native Method) [rt.jar:1.7.0_51]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) [rt.jar:1.7.0_51]
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:361) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:482) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:277) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:92) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.Module.loadModuleClass(Module.java:568) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.as.controller.OperationContext$RollbackHandler.<clinit>(OperationContext.java:899) [jboss-as-controller-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.controller.AbstractOperationContext.completeStep(AbstractOperationContext.java:300) [jboss-as-controller-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.server.operations.SystemPropertyAddHandler.execute(SystemPropertyAddHandler.java:114) [jboss-as-server-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:601) [jboss-as-controller-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.controller.AbstractOperationContext.doCompleteStep(AbstractOperationContext.java:479) [jboss-as-controller-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.controller.AbstractOperationContext.completeStepInternal(AbstractOperationContext.java:283) [jboss-as-controller-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:278) [jboss-as-controller-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:288) [jboss-as-controller-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:291) [jboss-as-controller-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.server.ServerService.boot(ServerService.java:349) [jboss-as-server-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.server.ServerService.boot(ServerService.java:324) [jboss-as-server-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:253) [jboss-as-controller-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at java.lang.Thread.run(Thread.java:744) [rt.jar:1.7.0_51]

12:30:58,607 FATAL [org.jboss.as.server] (Controller Boot Thread) JBAS015957: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
12:30:58,619 INFO  [org.jboss.as] (MSC service thread 1-3) JBAS015950: JBoss EAP 6.2.3.GA (AS 7.3.3.Final-redhat-3) stopped in 8ms

**Comment by hodrigohamalho** [comment]
@crivano procura no standalone.xml a system property idp.url e pode remover essa linha.

Tenta subir de novo.
