### ISSUE TITLE
Problema na disponibilização de projetos com VRaptor

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#270]
@crivano 

   O deploy funciona apenas quando está "explodido", descompactado dentro da pasta deploy, requisito este, que não irá atender aos ambientes de homologação e produção. Ocorre em todos os módulos migrados e é impeditivo (o projeto não sobe).

   O problema aparentemente é no scanner do VRaptor, e é possível reproduzir o problema de duas maneiras: realizando deploy da versão pela interface web ou fazendo deploy do war (compactado) pela pasta deployments.

 O erro ocorre pois o pacote não se chama mais sigaex.war como ele tenta referenciar na estrutura de diretórios. Logo, não encontra os arquivos que procura.
  Veja a stack abaixo:

````
10:00:01,285 INFO  [com.google.inject.Guice] (ServerService Thread Pool -- 90) An exception was caught and reported. Message: java.io.FileNotFoundException: /content/sigaex.war/WEB-INF/classes (No such file or directory): br.com.caelum.vraptor.scan.ScannerException: Could not scan base packages
        at br.com.caelum.vraptor.scan.ScannotationComponentScanner.scanBasePackages(ScannotationComponentScanner.java:88) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.scan.ScannotationComponentScanner.scan(ScannotationComponentScanner.java:56) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.scan.WebAppBootstrapFactory.scannerFor(WebAppBootstrapFactory.java:81) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.scan.WebAppBootstrapFactory.create(WebAppBootstrapFactory.java:51) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.ioc.guice.GuiceProvider$2.configure(GuiceProvider.java:122) [vraptor-3.5.4.jar:]
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223) [guice-3.0.jar:]
        at com.google.inject.spi.Elements.getElements(Elements.java:101) [guice-3.0.jar:]
        at com.google.inject.spi.Elements.getElements(Elements.java:92) [guice-3.0.jar:]
        at com.google.inject.util.Modules$RealOverriddenModuleBuilder$1.configure(Modules.java:172) [guice-3.0.jar:]
        at com.google.inject.AbstractModule.configure(AbstractModule.java:59) [guice-3.0.jar:]
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223) [guice-3.0.jar:]
        at com.google.inject.spi.Elements.getElements(Elements.java:101) [guice-3.0.jar:]
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133) [guice-3.0.jar:]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103) [guice-3.0.jar:]
        at com.google.inject.Guice.createInjector(Guice.java:95) [guice-3.0.jar:]
        at com.google.inject.Guice.createInjector(Guice.java:83) [guice-3.0.jar:]
        at br.com.caelum.vraptor.ioc.guice.GuiceProvider.start(GuiceProvider.java:97) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.VRaptor.init(VRaptor.java:121) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.VRaptor.init(VRaptor.java:115) [vraptor-3.5.4.jar:]
        at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:416) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:3225) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:3791) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.jboss.as.web.deployment.WebDeploymentService.doStart(WebDeploymentService.java:156) [jboss-as-web-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
        at org.jboss.as.web.deployment.WebDeploymentService.access$000(WebDeploymentService.java:60) [jboss-as-web-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
        at org.jboss.as.web.deployment.WebDeploymentService$1.run(WebDeploymentService.java:93) [jboss-as-web-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [rt.jar:1.7.0_79]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [rt.jar:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_79]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_79]
        at org.jboss.threads.JBossThread.run(JBossThread.java:122)
Caused by: java.io.FileNotFoundException: /content/sigaex.war/WEB-INF/classes (No such file or directory)
        at java.io.FileInputStream.open(Native Method) [rt.jar:1.7.0_79]
        at java.io.FileInputStream.<init>(FileInputStream.java:146) [rt.jar:1.7.0_79]
        at java.io.FileInputStream.<init>(FileInputStream.java:101) [rt.jar:1.7.0_79]
        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90) [rt.jar:1.7.0_79]
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188) [rt.jar:1.7.0_79]
        at java.net.URL.openStream(URL.java:1037) [rt.jar:1.7.0_79]
        at org.scannotation.archiveiterator.FileProtocolIteratorFactory.create(FileProtocolIteratorFactory.java:23) [scannotation-1.0.2.jar:]
        at org.scannotation.archiveiterator.IteratorFactory.create(IteratorFactory.java:40) [scannotation-1.0.2.jar:]
        at org.scannotation.AnnotationDB.scanArchives(AnnotationDB.java:291) [scannotation-1.0.2.jar:]
        at br.com.caelum.vraptor.scan.ScannotationComponentScanner.scanPackage(ScannotationComponentScanner.java:106) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.scan.ScannotationComponentScanner.scanBasePackages(ScannotationComponentScanner.java:83) [vraptor-3.5.4.jar:]
        ... 30 more
````

**Comment by kmacedovarela** [comment]
Resolvido.
0f6dd94217b8e816c08098985a141b71e72b1cd0
