### ISSUE TITLE
SIGA-DOC: Relatórios de formulários está apresentando erro

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#285]
O seguinte erro ocorre ao tentar executar o relatório:

your controller raised an exception

net.sf.jasperreports.engine.design.JRDesignStyle.setBorder(B)V

javax.servlet.ServletException: your controller raised an exception
	at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:105)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at br.gov.jfrj.siga.hibernate.ExThreadFilter.doFiltro(ExThreadFilter.java:92)
	at br.gov.jfrj.siga.hibernate.ExThreadFilter.executaFiltro(ExThreadFilter.java:83)
	at br.gov.jfrj.siga.hibernate.ExThreadFilter.doFilter(ExThreadFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:499)
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: net.sf.jasperreports.engine.design.JRDesignStyle.setBorder(B)V
	at ar.com.fdvs.dj.domain.Style.transform(Style.java:220)
	at ar.com.fdvs.dj.core.layout.AbstractLayoutManager.addStyleToDesign(AbstractLayoutManager.java:220)
	at ar.com.fdvs.dj.core.layout.AbstractLayoutManager.ensureDJStyles(AbstractLayoutManager.java:200)
	at ar.com.fdvs.dj.core.layout.AbstractLayoutManager.applyLayout(AbstractLayoutManager.java:130)
	at ar.com.fdvs.dj.core.DynamicJasperHelper.generateJasperReport(DynamicJasperHelper.java:453)
	at ar.com.fdvs.dj.core.DynamicJasperHelper.generateJasperPrint(DynamicJasperHelper.java:234)
	at br.gov.jfrj.relatorio.dinamico.AbstractRelatorioBaseBuilder.getRelatorioJasperPrint(AbstractRelatorioBaseBuilder.java:178)
	at br.gov.jfrj.relatorio.dinamico.RelatorioRapido.getRelatorioJasperPrint(RelatorioRapido.java:160)
	at br.gov.jfrj.relatorio.dinamico.RelatorioTemplate.getRelatorioPDF(RelatorioTemplate.java:267)
	at br.gov.jfrj.siga.vraptor.ExRelatorioController.aRelFormularios(ExRelatorioController.java:247)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at br.com.caelum.vraptor.interceptor.ExecuteMethodInterceptor.intercept(ExecuteMethodInterceptor.java:61)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.ParametersInstantiatorInterceptor.intercept(ParametersInstantiatorInterceptor.java:96)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:59)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:56)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.ExceptionHandlerInterceptor.intercept(ExceptionHandlerInterceptor.java:67)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.InstantiateInterceptor.intercept(InstantiateInterceptor.java:48)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:56)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.util.jpa.JPATransactionInterceptor.intercept(JPATransactionInterceptor.java:54)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.ResourceLookupInterceptor.intercept(ResourceLookupInterceptor.java:69)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.EnhancedRequestExecution.execute(EnhancedRequestExecution.java:44)
	at br.com.caelum.vraptor.VRaptor$1.insideRequest(VRaptor.java:95)
	at br.com.caelum.vraptor.ioc.guice.GuiceProvider.provideForRequest(GuiceProvider.java:82)
	at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:101)
	... 19 more

**Comment by crivano** [comment]
@kmacedovarela e @hodrigohamalho , esse deve ser um erro de ambiente, pois não ocorre na minha instância de desenvolvimento. Será que vocês têm como testar aí?

**Comment by hodrigohamalho** [comment]
@crivano como gera esse relatório?

**Comment by crivano** [comment]
@hodrigohamalho , basta entrar em: http://classec250.corp.jfrj.gov.br:8380/sigaex/app/expediente/rel/relRelatorios?nomeArquivoRel=relFormularios.jsp e clicar "Gerar".

**Comment by kmacedovarela** [comment]
@crivano,
É possivel que seja conflito de bibliotecas sim. O problema será analisado.

Trecho que indica classe possívelmente duplicada:
java.lang.NoSuchMethodError: net.sf.jasperreports.engine.design.JRDesignStyle.setBorder

**Comment by crivano** [comment]
@kmacedovarela OK, no aguardo...

**Comment by kmacedovarela** [comment]
@crivano o problema é que dentro do SigaEX estão empacotadas duas versões do jasper reports:

jasperreports-3.5.1.jar e 
jasperreports-5.1.0.jar

Sendo o jasperreports 3 incluido pelo sigaex e o 5 pelo siga-cp. Esse problema é solucionado ajustando as dependências no pom.xml.

Devemos executar a correção?

**Comment by crivano** [comment]
Pode deixar que sendo um problema de pom, eu mesmo tentarei resolver. Obrigado.

**Comment by kmacedovarela** [comment]
Isso um dia já foi resolvido. #191

**Comment by crivano** [comment]
O problema é que resolveram usando a versão mais antiga, e o ideal seria padronizar na versão mais nova. Vou tentar adaptar o código para que funcione com a 5.1.0.

**Comment by crivano** [comment]
Agora entendo porque foi resolvido mantendo as duas versões. Tentei remover mas foi ficando cada vez mais complicado. Desisti e reapliquei a solução #191.
