### ISSUE TITLE
SIGA-WF: erro ao criar workflow

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#294]
O erro abaixo está ocorrendo ao criar uma SEC ao criar o workflow no siga-dev. Em desenvolvimento funcionou corretamente.

Erro ao assinar documento.
 

javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: org.apache.jasper.el.JspELException: /paginas/expediente/modelos/sec.jsp(134,3) '${f:criarWorkflow('Contratação: fase de análise', doc, cadastrante, titular, lotaCadastrante, lotaTitular)}' JBWEB006013: Error calling function ''f:criarWorkflow'' 

 

br.gov.jfrj.siga.base.AplicacaoException: Erro ao assinar documento.
	at br.gov.jfrj.siga.ex.bl.ExBL.simularAssinaturaDocumento(ExBL.java:1972)
	at br.gov.jfrj.siga.vraptor.ExMovimentacaoController.aSimularAssinatura(ExMovimentacaoController.java:2455)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at br.com.caelum.vraptor.interceptor.ExecuteMethodInterceptor.intercept(ExecuteMethodInterceptor.java:61)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.ParametersInstantiatorInterceptor.intercept(ParametersInstantiatorInterceptor.java:96)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:59)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.ExceptionHandlerInterceptor.intercept(ExceptionHandlerInterceptor.java:67)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.InstantiateInterceptor.intercept(InstantiateInterceptor.java:48)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:56)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:56)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.util.jpa.JPATransactionInterceptor.intercept(JPATransactionInterceptor.java:54)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.ResourceLookupInterceptor.intercept(ResourceLookupInterceptor.java:69)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.EnhancedRequestExecution.execute(EnhancedRequestExecution.java:44)
	at br.com.caelum.vraptor.VRaptor$1.insideRequest(VRaptor.java:95)
	at br.com.caelum.vraptor.ioc.guice.GuiceProvider.provideForRequest(GuiceProvider.java:82)
	at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at br.gov.jfrj.siga.hibernate.ExThreadFilter.doFiltro(ExThreadFilter.java:92)
	at br.gov.jfrj.siga.hibernate.ExThreadFilter.executaFiltro(ExThreadFilter.java:83)
	at br.gov.jfrj.siga.hibernate.ExThreadFilter.doFilter(ExThreadFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:499)
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: org.apache.jasper.el.JspELException: /paginas/expediente/modelos/sec.jsp(134,3) '${f:criarWorkflow('Contratação: fase de análise', doc, cadastrante, titular, lotaCadastrante, lotaTitular)}' JBWEB006013: Error calling function ''f:criarWorkflow''
	at org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:841)
	at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:774)
	at org.apache.jsp.WEB_002dINF.page.exDocumento.processa_005fmodelo_jsp._jspService(processa_005fmodelo_jsp.java:81)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:365)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:309)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:242)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:832)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:718)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:655)
	at br.gov.jfrj.siga.util.ExProcessadorModelo.processarModelo(ExProcessadorModelo.java:63)
	at br.gov.jfrj.siga.ex.bl.ExBL.processarModelo(ExBL.java:5265)
	at br.gov.jfrj.siga.ex.bl.ExBL.processarComandosEmTag(ExBL.java:2500)
	at br.gov.jfrj.siga.ex.bl.ExBL.simularAssinaturaDocumento(ExBL.java:1961)
	... 56 more
Caused by: javax.servlet.jsp.JspException: org.apache.jasper.el.JspELException: /paginas/expediente/modelos/sec.jsp(134,3) '${f:criarWorkflow('Contratação: fase de análise', doc, cadastrante, titular, lotaCadastrante, lotaTitular)}' JBWEB006013: Error calling function ''f:criarWorkflow''
	at org.apache.jsp.paginas.expediente.modelos.sec_jsp$Helper.invoke(sec_jsp.java:806)
	at org.apache.jsp.tag.web.mod.assinatura_tag._jspx_meth_c_005fif_005f0(assinatura_tag.java:103)
	at org.apache.jsp.tag.web.mod.assinatura_tag.doTag(assinatura_tag.java:65)
	at org.apache.jsp.paginas.expediente.modelos.sec_jsp._jspx_meth_mod_005fassinatura_005f0(sec_jsp.java:501)
	at org.apache.jsp.paginas.expediente.modelos.sec_jsp.access$2(sec_jsp.java:492)
	at org.apache.jsp.paginas.expediente.modelos.sec_jsp$Helper.invoke0(sec_jsp.java:587)
	at org.apache.jsp.paginas.expediente.modelos.sec_jsp$Helper.invoke(sec_jsp.java:786)
	at org.apache.jsp.tag.web.mod.modelo_tag.doTag(modelo_tag.java:206)
	at org.apache.jsp.paginas.expediente.modelos.sec_jsp._jspx_meth_mod_005fmodelo_005f0(sec_jsp.java:122)
	at org.apache.jsp.paginas.expediente.modelos.sec_jsp._jspService(sec_jsp.java:98)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:365)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:309)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:242)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:832)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:718)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:655)
	at org.apache.taglibs.standard.tag.common.core.ImportSupport.acquireString(ImportSupport.java:347)
	at org.apache.taglibs.standard.tag.common.core.ImportSupport.doEndTag(ImportSupport.java:204)
	at org.apache.jsp.WEB_002dINF.page.exDocumento.processa_005fmodelo_jsp._jspx_meth_c_005fimport_005f0(processa_005fmodelo_jsp.java:213)
	at org.apache.jsp.WEB_002dINF.page.exDocumento.processa_005fmodelo_jsp._jspService(processa_005fmodelo_jsp.java:74)
	... 71 more
Caused by: org.apache.jasper.el.JspELException: /paginas/expediente/modelos/sec.jsp(134,3) '${f:criarWorkflow('Contratação: fase de análise', doc, cadastrante, titular, lotaCadastrante, lotaTitular)}' JBWEB006013: Error calling function ''f:criarWorkflow''
	at org.apache.jasper.el.JspValueExpression.getValue(JspValueExpression.java:107)
	at org.apache.jsp.paginas.expediente.modelos.sec_jsp._jspx_meth_c_005fset_005f1(sec_jsp.java:550)
	at org.apache.jsp.paginas.expediente.modelos.sec_jsp._jspx_meth_c_005fif_005f3(sec_jsp.java:522)
	at org.apache.jsp.paginas.expediente.modelos.sec_jsp.access$12(sec_jsp.java:506)
	at org.apache.jsp.paginas.expediente.modelos.sec_jsp$Helper.invoke4(sec_jsp.java:765)
	at org.apache.jsp.paginas.expediente.modelos.sec_jsp$Helper.invoke(sec_jsp.java:798)
	... 95 more
Caused by: javax.xml.ws.WebServiceException: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.jaxws.ServiceImpl.(ServiceImpl.java:151)
	at org.jboss.wsf.stack.cxf.client.ProviderImpl$JBossWSServiceImpl.(ProviderImpl.java:563)
	at org.jboss.wsf.stack.cxf.client.ProviderImpl.createServiceDelegate(ProviderImpl.java:258)
	at javax.xml.ws.Service.(Service.java:57)
	at javax.xml.ws.Service.create(Service.java:687)
	at br.gov.jfrj.siga.Service.getService(Service.java:95)
	at br.gov.jfrj.siga.Service.getWfService(Service.java:51)
	at br.gov.jfrj.siga.ex.bl.ExBL.criarWorkflow(ExBL.java:3518)
	at br.gov.jfrj.siga.ex.util.FuncoesEL.criarWorkflow(FuncoesEL.java:725)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.el.parser.AstFunction.getValue(AstFunction.java:110)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:189)
	at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at org.apache.jasper.el.JspValueExpression.getValue(JspValueExpression.java:101)
	... 100 more
Caused by: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.wsdl11.WSDLServiceFactory.(WSDLServiceFactory.java:100)
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:204)
	at org.apache.cxf.jaxws.ServiceImpl.(ServiceImpl.java:149)
	... 116 more
Caused by: javax.wsdl.WSDLException: WSDLException: faultCode=PARSER_ERROR: Problem parsing 'http://10.10.0.66:8480/sigawf/servicos/WfService?wsdl'.: java.net.ConnectException: Connection refused
	at com.ibm.wsdl.xml.WSDLReaderImpl.getDocument(WSDLReaderImpl.java:2111)
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2303)
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2335)
	at org.apache.cxf.wsdl11.WSDLManagerImpl.loadDefinition(WSDLManagerImpl.java:263)
	at org.apache.cxf.wsdl11.WSDLManagerImpl.getDefinition(WSDLManagerImpl.java:206)
	at org.apache.cxf.wsdl11.WSDLServiceFactory.(WSDLServiceFactory.java:98)
	... 118 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:997)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:851)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:986)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:143)
	at org.apache.xerces.parsers.XML11Configuration.parse(XML11Configuration.java:802)
	at org.apache.xerces.parsers.XML11Configuration.parse(XML11Configuration.java:768)
	at org.apache.xerces.parsers.XMLParser.parse(XMLParser.java:108)
	at org.apache.xerces.parsers.DOMParser.parse(DOMParser.java:230)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:285)
	at com.ibm.wsdl.xml.WSDLReaderImpl.getDocument(WSDLReaderImpl.java:2101)
	... 123 more

**Comment by crivano** [comment]
Resolvido.
