### ISSUE TITLE
[Siga-Gc] Intermitente - Erro ao clicar em "Exibir movimentações" 

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#342]
Dos testes que fiz, só deu erro para o caso específico do conhecimento TMPGC-2667 (http://siga-dev:8380/sigagc/app/exibir/TMPGC2667):

- Link com erro: http://siga-dev:8380/sigagc/app/movimentacoes/TMPGC2667

- Log de erro:

javax.servlet.ServletException: javax.servlet.jsp.JspException: java.lang.NumberFormatException: For input string: "Anexação de arquivo"

javax.servlet.jsp.JspException: java.lang.NumberFormatException: For input string: "Anexação de arquivo"

br.com.caelum.vraptor.proxy.ProxyInvocationException: javax.servlet.ServletException: javax.servlet.jsp.JspException: java.lang.NumberFormatException: For input string: "Anexação de arquivo"
	at br.gov.jfrj.siga.vraptor.SigaLogicResult$1.intercept(SigaLogicResult.java:120)
	at br.com.caelum.vraptor.proxy.JavassistProxifier$2.invoke(JavassistProxifier.java:95)
	at br.gov.jfrj.siga.gc.vraptor.AppController_$$_jvst96b_153.exibir(AppController_$$_jvst96b_153.java)
	at br.gov.jfrj.siga.gc.vraptor.AppController.movimentacoes(AppController.java:820)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at br.com.caelum.vraptor.interceptor.ExecuteMethodInterceptor.intercept(ExecuteMethodInterceptor.java:61)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.ParametersInstantiatorInterceptor.intercept(ParametersInstantiatorInterceptor.java:96)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:59)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.ExceptionHandlerInterceptor.intercept(ExceptionHandlerInterceptor.java:67)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:56)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.InstantiateInterceptor.intercept(InstantiateInterceptor.java:48)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:56)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:56)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.util.jpa.JPATransactionInterceptor.intercept(JPATransactionInterceptor.java:54)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.ResourceLookupInterceptor.intercept(ResourceLookupInterceptor.java:69)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.EnhancedRequestExecution.execute(EnhancedRequestExecution.java:44)
	at br.com.caelum.vraptor.VRaptor$1.insideRequest(VRaptor.java:95)
	at br.com.caelum.vraptor.ioc.guice.GuiceProvider.provideForRequest(GuiceProvider.java:82)
	at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:499)
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.servlet.ServletException: javax.servlet.jsp.JspException: java.lang.NumberFormatException: For input string: "Anexação de arquivo"
	at org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:841)
	at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:774)
	at org.apache.jsp.WEB_002dINF.page.app.exibir_jsp._jspService(exibir_jsp.java:101)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:365)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:309)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:242)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:832)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:620)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:553)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:482)
	at br.gov.jfrj.siga.vraptor.SigaLogicResult$1.intercept(SigaLogicResult.java:111)
	... 55 more
Caused by: java.lang.NumberFormatException: For input string: "Anexação de arquivo"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1268)
	at java.lang.Double.valueOf(Double.java:504)
	at java.lang.Double.(Double.java:597)
	at org.apache.el.lang.ELArithmetic$DoubleDelegate.coerce(ELArithmetic.java:150)
	at org.apache.el.lang.ELArithmetic.coerce(ELArithmetic.java:401)
	at org.apache.el.lang.ELArithmetic.add(ELArithmetic.java:270)
	at org.apache.el.parser.AstPlus.getValue(AstPlus.java:41)
	at org.apache.el.parser.AstPlus.getValue(AstPlus.java:39)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:189)
	at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at org.apache.jasper.el.JspValueExpression.getValue(JspValueExpression.java:101)
	at org.apache.jsp.WEB_002dINF.page.app.exibir_jsp._jspx_meth_c_005fset_005f3(exibir_jsp.java:895)
	at org.apache.jsp.WEB_002dINF.page.app.exibir_jsp._jspx_meth_c_005fwhen_005f2(exibir_jsp.java:867)
	at org.apache.jsp.WEB_002dINF.page.app.exibir_jsp._jspx_meth_c_005fchoose_005f1(exibir_jsp.java:827)
	at org.apache.jsp.WEB_002dINF.page.app.exibir_jsp._jspx_meth_c_005fwhen_005f1(exibir_jsp.java:797)
	at org.apache.jsp.WEB_002dINF.page.app.exibir_jsp._jspx_meth_c_005fchoose_005f0(exibir_jsp.java:708)
	at org.apache.jsp.WEB_002dINF.page.app.exibir_jsp._jspx_meth_c_005fforEach_005f3(exibir_jsp.java:623)
	at org.apache.jsp.WEB_002dINF.page.app.exibir_jsp._jspx_meth_c_005fif_005f6(exibir_jsp.java:583)
	at org.apache.jsp.WEB_002dINF.page.app.exibir_jsp.access$8(exibir_jsp.java:546)
	at org.apache.jsp.WEB_002dINF.page.app.exibir_jsp$Helper.invoke0(exibir_jsp.java:1690)
	at org.apache.jsp.WEB_002dINF.page.app.exibir_jsp$Helper.invoke(exibir_jsp.java:1726)
	at org.apache.jsp.tag.meta.http_003a.localhost.jeetags.pagina_tag.doTag(pagina_tag.java:199)
	at org.apache.jsp.WEB_002dINF.page.app.exibir_jsp._jspx_meth_siga_005fpagina_005f0(exibir_jsp.java:118)
	at org.apache.jsp.WEB_002dINF.page.app.exibir_jsp._jspService(exibir_jsp.java:94)
	... 68 more

**Comment by Chrystinne** [comment]
Descobri exatamente quando dá esse erro. Passo a passo:

- Clicar em Editar;
- Clicar em "remover" anexo;
- Clicar em "gravar";
- Clicar em "Exibir movimentações";

**Comment by Chrystinne** [comment]
Resolvido.
