### ISSUE TITLE
Problema impeditivo no JBPM

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#343]
Está acontecendo um erro entre o JBPM e o Hibernate:

Encontrei algum material na internet:
https://developer.jboss.org/thread/115533?start=0&tstart=0

```
11:38:31,975 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/sigawf].[default]] (http-localhost/127.0.0.1:8080-1) JBWEB000236: Servlet.service() for servlet default threw exception: org.hibernate.HibernateException: Unable to resolve entity name from Class [org.jbpm.context.exe.variableinstance.UnpersistableInstance] expected instance/subclass of [org.jbpm.context.exe.VariableInstance]
	at org.hibernate.tuple.entity.PojoEntityTuplizer.determineConcreteSubclassEntityName(PojoEntityTuplizer.java:553) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.persister.entity.AbstractEntityPersister.getSubclassEntityPersister(AbstractEntityPersister.java:4590) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.internal.SessionImpl.getEntityPersister(SessionImpl.java:1448) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.engine.internal.ForeignKeys.isTransient(ForeignKeys.java:208) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.event.internal.AbstractSaveEventListener.getEntityState(AbstractSaveEventListener.java:497) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:100) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:90) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:735) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:727) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.engine.spi.CascadingAction$5.cascade(CascadingAction.java:258) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:399) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:342) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:208) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.engine.internal.Cascade.cascadeCollectionElements(Cascade.java:429) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.engine.internal.Cascade.cascadeCollection(Cascade.java:369) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:345) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:208) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:165) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.event.internal.AbstractFlushingEventListener.cascadeOnFlush(AbstractFlushingEventListener.java:162) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.event.internal.AbstractFlushingEventListener.prepareEntityFlushes(AbstractFlushingEventListener.java:153) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:89) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:58) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1211) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1291) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.internal.QueryImpl.executeUpdate(QueryImpl.java:116) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.jbpm.db.JobSession.deleteTimersByName(JobSession.java:206) [jbpm-jpdl-3.2.10.SP3_seam2.jar:3.2.10.SP3_seam2]
	at org.jbpm.scheduler.db.DbSchedulerService.deleteTimersByName(DbSchedulerService.java:63) [jbpm-jpdl-3.2.10.SP3_seam2.jar:3.2.10.SP3_seam2]
	at org.jbpm.scheduler.def.CancelTimerAction.execute(CancelTimerAction.java:48) [jbpm-jpdl-3.2.10.SP3_seam2.jar:3.2.10.SP3_seam2]
	at org.jbpm.graph.def.GraphElement.executeActionImpl(GraphElement.java:300) [jbpm-jpdl-3.2.10.SP3_seam2.jar:3.2.10.SP3_seam2]
	at org.jbpm.graph.def.GraphElement.executeAction(GraphElement.java:267) [jbpm-jpdl-3.2.10.SP3_seam2.jar:3.2.10.SP3_seam2]
	at org.jbpm.graph.def.GraphElement.executeActions(GraphElement.java:240) [jbpm-jpdl-3.2.10.SP3_seam2.jar:3.2.10.SP3_seam2]
	at org.jbpm.graph.def.GraphElement.fireAndPropagateEvent(GraphElement.java:206) [jbpm-jpdl-3.2.10.SP3_seam2.jar:3.2.10.SP3_seam2]
	at org.jbpm.graph.def.GraphElement.fireEvent(GraphElement.java:188) [jbpm-jpdl-3.2.10.SP3_seam2.jar:3.2.10.SP3_seam2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_71]
	at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_71]
	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:192) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.jbpm.taskmgmt.def.Task_$$_jvstf95_ed.fireEvent(Task_$$_jvstf95_ed.java) [jbpm-jpdl-3.2.10.SP3_seam2.jar:3.2.10.SP3_seam2]
	at org.jbpm.taskmgmt.exe.TaskInstance.end(TaskInstance.java:421) [jbpm-jpdl-3.2.10.SP3_seam2.jar:3.2.10.SP3_seam2]
	at br.gov.jfrj.siga.wf.vraptor.AppController.executeTask(AppController.java:257) [classes:]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_71]
	at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_71]
	at br.com.caelum.vraptor.interceptor.ExecuteMethodInterceptor.intercept(ExecuteMethodInterceptor.java:61) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.interceptor.InstantiateInterceptor.intercept(InstantiateInterceptor.java:48) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.interceptor.ParametersInstantiatorInterceptor.intercept(ParametersInstantiatorInterceptor.java:96) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:59) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.interceptor.ExceptionHandlerInterceptor.intercept(ExceptionHandlerInterceptor.java:67) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:56) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
	at br.gov.jfrj.siga.wf.vraptor.WfInterceptor.intercept(WfInterceptor.java:37) [classes:]
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:56) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.util.jpa.JPATransactionInterceptor.intercept(JPATransactionInterceptor.java:54) [vraptor-jpa-1.0.2.jar:]
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.interceptor.ResourceLookupInterceptor.intercept(ResourceLookupInterceptor.java:69) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.core.EnhancedRequestExecution.execute(EnhancedRequestExecution.java:44) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.VRaptor$1.insideRequest(VRaptor.java:95) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.ioc.guice.GuiceProvider.provideForRequest(GuiceProvider.java:82) [vraptor-3.5.4.jar:]
	at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:101) [vraptor-3.5.4.jar:]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:499) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_71]
```

**Comment by crivano** [comment]
Já corrigi.

**Comment by kmacedovarela** [comment]
Seria possível colocar o commit de referência caso ocorra novamente?

**Comment by crivano** [comment]
https://github.com/projeto-siga/siga/commit/019b2da2d161c05192a6a227fe8a78408b2e4750
