### ISSUE TITLE
WF: erro ao enviar e-mail 390796

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#410]
O seguinte erro ocorre ao tentar enviar o e-mail do job associado à task instance (id 390796)

```
javax.servlet.ServletException: org.jbpm.jpdl.el.ELException: An error occurred while evaluating function "wf:getGroup"
	at br.gov.jfrj.siga.wf.util.WfJobExecutorThread.executeJob(WfJobExecutorThread.java:105)
	at org.jbpm.job.executor.JobExecutorThread.run(JobExecutorThread.java:51)
Caused by: org.jbpm.jpdl.el.ELException: An error occurred while evaluating function "wf:getGroup"
	at org.jbpm.jpdl.el.impl.Logger.logError(Logger.java:485)
	at org.jbpm.jpdl.el.impl.Logger.logError(Logger.java:546)
	at org.jbpm.jpdl.el.impl.FunctionInvocation.evaluate(FunctionInvocation.java:175)
	at org.jbpm.jpdl.el.impl.ExpressionEvaluatorImpl.evaluate(ExpressionEvaluatorImpl.java:264)
	at org.jbpm.jpdl.el.impl.ExpressionEvaluatorImpl.evaluate(ExpressionEvaluatorImpl.java:191)
	at org.jbpm.jpdl.el.impl.JbpmExpressionEvaluator.evaluate(JbpmExpressionEvaluator.java:86)
	at org.jbpm.mail.Mail.evaluate(Mail.java:172)
	at org.jbpm.mail.Mail.evaluateActors(Mail.java:110)
	at org.jbpm.mail.Mail.collectRecipients(Mail.java:101)
	at org.jbpm.mail.Mail.getRecipients(Mail.java:78)
	at org.jbpm.mail.Mail.send(Mail.java:203)
	at br.gov.jfrj.siga.wf.util.WfMail.send(WfMail.java:108)
	at org.jbpm.mail.Mail.execute(Mail.java:74)
	at br.gov.jfrj.siga.wf.util.WfMail.execute(WfMail.java:97)
	at org.jbpm.graph.def.Action.execute(Action.java:117)
	at sun.reflect.GeneratedMethodAccessor1695.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:192)
	at org.jbpm.graph.def.Action_$$_jvstab4_132.execute(Action_$$_jvstab4_132.java)
	at org.jbpm.graph.def.GraphElement.executeActionImpl(GraphElement.java:300)
	at org.jbpm.graph.def.GraphElement.executeAction(GraphElement.java:274)
	at sun.reflect.GeneratedMethodAccessor1692.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:192)
	at org.jbpm.taskmgmt.def.Task_$$_jvstab4_12f.executeAction(Task_$$_jvstab4_12f.java)
	at org.jbpm.job.Timer.execute(Timer.java:56)
	at br.gov.jfrj.siga.wf.util.WfJobExecutorThread.executeJob(WfJobExecutorThread.java:93)
	... 1 more
Caused by: java.lang.NullPointerException
	at br.gov.jfrj.siga.wf.util.WfFunctionMapper.wf_getGroup(WfFunctionMapper.java:97)
	at sun.reflect.GeneratedMethodAccessor1703.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jbpm.jpdl.el.impl.FunctionInvocation.evaluate(FunctionInvocation.java:173)
	... 27 more

```

**Comment by Markenson** [comment]
Resolvido em 9906b12e16eead37a6060fd5.
