### ISSUE TITLE
SINC: Importador XML não funciona na versão vraptor

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#441]
O seguinte esse ocorre ao tentar importar o XML

```
org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.spi.CacheImplementor]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:186)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:150)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:131)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:264)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1750)
        at br.gov.jfrj.siga.model.dao.HibernateUtil.configurarHibernate(HibernateUtil.java:249)
        at br.gov.jfrj.importar.SigaCpSinc.run(SigaCpSinc.java:465)
        at br.gov.jfrj.importar.SigaCpSinc.main(SigaCpSinc.java:448)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:313)
        at com.simontuffs.onejar.Boot.main(Boot.java:161)
Caused by: org.hibernate.cache.CacheException: Unable to start region factory
        at org.hibernate.cache.infinispan.InfinispanRegionFactory.start(InfinispanRegionFactory.java:323)
        at org.hibernate.internal.CacheImpl.<init>(CacheImpl.java:70)
        at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:40)
        at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:35)
        at org.hibernate.service.internal.SessionFactoryServiceRegistryImpl.initiateService(SessionFactoryServiceRegistryImpl.java:91)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:176)
        ... 13 more
Caused by: java.lang.NullPointerException
        at org.jboss.as.jpa.hibernate4.infinispan.InfinispanRegionFactory.createCacheManager(InfinispanRegionFactory.java:83)
        at org.hibernate.cache.infinispan.InfinispanRegionFactory.start(InfinispanRegionFactory.java:308)
        ... 18 more
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:313)
        at com.simontuffs.onejar.Boot.main(Boot.java:161)
Caused by: java.lang.ExceptionInInitializerError
        at br.gov.jfrj.siga.model.dao.HibernateUtil.configurarHibernate(HibernateUtil.java:257)
        at br.gov.jfrj.importar.SigaCpSinc.run(SigaCpSinc.java:465)
        at br.gov.jfrj.importar.SigaCpSinc.main(SigaCpSinc.java:448)
        ... 6 more
Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.spi.CacheImplementor]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:186)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:150)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:131)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:264)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1750)
        at br.gov.jfrj.siga.model.dao.HibernateUtil.configurarHibernate(HibernateUtil.java:249)
        ... 8 more
Caused by: org.hibernate.cache.CacheException: Unable to start region factory
        at org.hibernate.cache.infinispan.InfinispanRegionFactory.start(InfinispanRegionFactory.java:323)
        at org.hibernate.internal.CacheImpl.<init>(CacheImpl.java:70)
        at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:40)
        at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:35)
        at org.hibernate.service.internal.SessionFactoryServiceRegistryImpl.initiateService(SessionFactoryServiceRegistryImpl.java:91)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:176)
        ... 13 more
Caused by: java.lang.NullPointerException
        at org.jboss.as.jpa.hibernate4.infinispan.InfinispanRegionFactory.createCacheManager(InfinispanRegionFactory.java:83)
        at org.hibernate.cache.infinispan.InfinispanRegionFactory.start(InfinispanRegionFactory.java:308)
        ... 18 more
```

**Comment by Markenson** [comment]
Como podemos tratar esse gerenciamento de arquivos do cache de segundo nível via Dockerfile (o que manteria a documentação adequada para tratar do cache de segundo nível), vou trabalhar com o ajuste das aplicações não-web. Reverti o commit e reabri a issue.

**Comment by Markenson** [comment]
Desativação do cache de segundo nível apenas para sincronizador implementado.
