### ISSUE TITLE
GERAL: Erro de cache de segundo nível

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#473]
Ao fazer um teste de carga com 30 usuários, o sistema apresentou o erro abaixo. O problema parece estar relacionando ao cache de segundo nível.

```
ref: https://access.redhat.com/solutions/1327563

Infinispan is used as the level two cache for Hibernate

The exception indicates that multiple threads were attempting to update the Infinispan cache and the locks (obtained and pending) for these threads result in a deadlock. One thread has been chosen as victim, its locks have been released and the exception is raised to application code.

```

Erro:
```
16:14:17,718 ERROR [org.infinispan.transaction.TransactionCoordinator] (http-/0.0.0.0:8680-3) Error while processing prepare: org.infinispan.util.concurre  nt.TimeoutException: Unable to acquire lock after [0 milliseconds] on key [sql: select dpsubstitu0_.ID_SUBSTITUICAO as ID_SUBST1_29_, dpsubstitu0_.DT_INI_  SUBST as DT_INI_S2_29_, dpsubstitu0_.DT_FIM_SUBST as DT_FIM_S3_29_, dpsubstitu0_.ID_TITULAR as ID_TITUL4_29_, dpsubstitu0_.ID_LOTA_TITULAR as ID_LOTA_5_29  _, dpsubstitu0_.ID_SUBSTITUTO as ID_SUBST6_29_, dpsubstitu0_.ID_LOTA_SUBSTITUTO as ID_LOTA_7_29_, dpsubstitu0_.ID_REG_INI as ID_REG_I8_29_, dpsubstitu0_.D  T_FIM_REG as DT_FIM_R9_29_, dpsubstitu0_.DT_INI_REG as DT_INI_10_29_ from CORPORATIVO.DP_SUBSTITUICAO dpsubstitu0_ where (dpsubstitu0_.DT_INI_SUBST<sysdat  e or dpsubstitu0_.DT_INI_SUBST is null) and (dpsubstitu0_.DT_FIM_SUBST>sysdate or dpsubstitu0_.DT_FIM_SUBST is null) and ((dpsubstitu0_.ID_SUBSTITUTO is n  ull) and (dpsubstitu0_.ID_LOTA_SUBSTITUTO in (select dplotacao1_.ID_LOTACAO from CORPORATIVO.DP_LOTACAO dplotacao1_ where dplotacao1_.ID_LOTACAO_INI=?)) o  r dpsubstitu0_.ID_SUBSTITUTO in (select dppessoa2_.ID_PESSOA from CORPORATIVO.DP_PESSOA dppessoa2_ where dppessoa2_.ID_PESSOA_INICIAL=?)) and (dpsubstitu0  _.DT_FIM_REG is null); parameters: ; named parameters: {idSubstitutoIni=308055, idLotaSubstitutoIni=33569}; transformer: org.hibernate.transform.Cacheable  ResultTransformer@110f2] for requestor [GlobalTransaction:<null>:730:local]! Lock held by [GlobalTransaction:<null>:729:local]
        at org.infinispan.util.concurrent.locks.LockManagerImpl.lock(LockManagerImpl.java:213)
        at org.infinispan.util.concurrent.locks.LockManagerImpl.acquireLock(LockManagerImpl.java:186)
--
        at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1165)
        at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:126)
        at com.arjuna.ats.jbossatx.BaseTransactionManagerDelegate.commit(BaseTransactionManagerDelegate.java:75)
        at org.jboss.tm.usertx.client.ServerVMClientUserTransaction.commit(ServerVMClientUserTransaction.java:167)
        at org.hibernate.engine.transaction.internal.jta.JtaTransaction.doCommit(JtaTransaction.java:154) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4  -redhat-1]
        at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:178) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.  2.7.SP4-redhat-1]
        at br.gov.jfrj.siga.model.dao.HibernateUtil.commitTransacao(HibernateUtil.java:108) [siga-base-1.2-SNAPSHOT.jar:]
        at br.gov.jfrj.siga.model.dao.ModeloDao.commitTransacao(ModeloDao.java:236) [siga-base-1.2-SNAPSHOT.jar:]
        at br.gov.jfrj.siga.util.HibernateThreadFilter.executaFiltro(HibernateThreadFilter.java:127) [classes:]
        at br.gov.jfrj.siga.util.HibernateThreadFilter.doFilter(HibernateThreadFilter.java:61) [classes:]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Fina  l-redhat-1]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat  -1]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:499) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.3.3.Final-redhat-3.j  ar:7.3.3.Final-redhat-3]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final  -redhat-1]
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_79]	
Caused by: javax.transaction.xa.XAException
        at org.infinispan.transaction.TransactionCoordinator.prepare(TransactionCoordinator.java:161)
        at org.infinispan.transaction.TransactionCoordinator.prepare(TransactionCoordinator.java:123)
        at org.infinispan.transaction.synchronization.SynchronizationAdapter.beforeCompletion(SynchronizationAdapter.java:68)
        ... 28 more

16:14:17,734 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/siga].[default]] (http-/0.0.0.0:8680-4) JBWEB000236: Servlet.servi  ce() for servlet default threw exception: br.gov.jfrj.siga.base.AplicacaoException: Erro gravando transação no banco de dados
        at br.gov.jfrj.siga.model.dao.HibernateUtil.commitTransacao(HibernateUtil.java:115) [siga-base-1.2-SNAPSHOT.jar:]
        at br.gov.jfrj.siga.model.dao.ModeloDao.commitTransacao(ModeloDao.java:236) [siga-base-1.2-SNAPSHOT.jar:]
--
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_79]
Caused by: org.hibernate.TransactionException: commit failed
        at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:185) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.  2.7.SP4-redhat-1]
        at br.gov.jfrj.siga.model.dao.HibernateUtil.commitTransacao(HibernateUtil.java:108) [siga-base-1.2-SNAPSHOT.jar:]
        ... 17 more
Caused by: org.hibernate.TransactionException: JTA commit failed:
        at org.hibernate.engine.transaction.internal.jta.JtaTransaction.doCommit(JtaTransaction.java:159) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4  -redhat-1]
        at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:178) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.  2.7.SP4-redhat-1]
        ... 18 more
Caused by: javax.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
        at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1177)
        at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:126)
        at com.arjuna.ats.jbossatx.BaseTransactionManagerDelegate.commit(BaseTransactionManagerDelegate.java:75)
        at org.jboss.tm.usertx.client.ServerVMClientUserTransaction.commit(ServerVMClientUserTransaction.java:167)
        at org.hibernate.engine.transaction.internal.jta.JtaTransaction.doCommit(JtaTransaction.java:154) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4  -redhat-1]
        ... 19 more
Caused by: org.infinispan.CacheException: Could not prepare.
        at org.infinispan.transaction.synchronization.SynchronizationAdapter.beforeCompletion(SynchronizationAdapter.java:70)
        at com.arjuna.ats.internal.jta.resources.arjunacore.SynchronizationImple.beforeCompletion(SynchronizationImple.java:76)
        at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.beforeCompletion(TwoPhaseCoordinator.java:273)
        at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:93)
        at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:162)
        at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1165)
        ... 23 more
Caused by: javax.transaction.xa.XAException
        at org.infinispan.transaction.TransactionCoordinator.prepare(TransactionCoordinator.java:161)
        at org.infinispan.transaction.TransactionCoordinator.prepare(TransactionCoordinator.java:123)
        at org.infinispan.transaction.synchronization.SynchronizationAdapter.beforeCompletion(SynchronizationAdapter.java:68)
        ... 28 more



16:14:17,740 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host]] (http-/0.0.0.0:8680-4) JBWEB000313: Exception processing error page   /WEB-INF/page/erroGeral.jsp: java.lang.IllegalStateException: JBWEB000029: Cannot reset buffer after response has been committed
        at org.apache.catalina.connector.Response.resetBuffer(Response.java:682) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.connector.Response.resetBuffer(Response.java:702) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:515) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:370) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final  -redhat-1]
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_79]

```

**Comment by Markenson** [comment]
Segundo a [documentacao de configuração do infinispan](https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6/html/Development_Guide_Governance/appe-Infinispan_Configuration.html) no site da Redhat, o default da configuração locking do cache é OPTIMISTIC e deve ser PESSIMISTIC se diversas aplicações estão atualizando o cache no mesmo nó. Além disso, de acordo com esse [comentário](https://bugzilla.redhat.com/show_bug.cgi?id=901162#c19) que trata do mesmo problema no jboss 6.2 a recomendação é colocar como PESSIMISTIC.

Baseando-me nisso, alterei a seguinte configuração no meu standalone.xml, conforme abaixo (acrescentei **locking="PESSIMISTIC"** no transaction) e o erro descrito nesta issue não ocorreu mais.

```
            <cache-container name="hibernate" default-cache="local-query" jndi-name="java:jboss/infinispan/hibernate" start="EAGER" module="org.jboss.as.jpa.hibernate:4">
                <local-cache name="entity">
                    <transaction mode="NON_XA" locking="PESSIMISTIC"/>
                    <eviction strategy="LRU" max-entries="10000"/>
                    <expiration max-idle="100000"/>
                </local-cache>
                <local-cache name="local-query">
                    <transaction mode="NONE"/>
                    <eviction strategy="LRU" max-entries="10000"/>
                    <expiration max-idle="100000"/>
                </local-cache>
                <local-cache name="timestamps">
                    <transaction mode="NONE"/>
                    <eviction strategy="NONE"/>
                </local-cache>
            </cache-container>
```

**Comment by kmacedovarela** [comment]
A recomendação é valida quando as aplicações estão na mesma instância. Nos ambientes de homologação e produção, esta configuração não é recomendada.

No exemplo acima foi realizada a configuração apenas no entity local-cache. Sugiro que faça esta modificação também no local-query, e apenas nos ambientes onde o siga está instalado em uma única instância standalone.
