### ISSUE TITLE
SIGA: Erro intermitente no teste de carga

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#474]
O André (G&P) reportou o erro abaixo no teste de carga (30 usuários). Parece que o arquivo pagina.tag não está disponível no class loader. Estranho é que o erro é intermitente.

```
16:09:26,404 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/siga].[jsp]] (http-/0.0.0.0:8680-2) JBWEB000236: Servlet.service()   for servlet jsp threw exception: java.lang.NoClassDefFoundError: org/apache/jsp/tag/meta/http_003a/localhost/jeetags/pagina_tag
        at org.apache.jsp.WEB_002dINF.page.principal.principal_jsp._jspx_meth_siga_005fpagina_005f0(principal_jsp.java:106)
        at org.apache.jsp.WEB_002dINF.page.principal.principal_jsp._jspService(principal_jsp.java:83)
--
        at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.interceptor.ResourceLookupInterceptor.intercept(ResourceLookupInterceptor.java:69) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.core.EnhancedRequestExecution.execute(EnhancedRequestExecution.java:44) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.VRaptor$1.insideRequest(VRaptor.java:95) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.ioc.guice.GuiceProvider.provideForRequest(GuiceProvider.java:82) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:101) [vraptor-3.5.4.jar:]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Fina  l-redhat-1]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat  -1]
        at br.gov.jfrj.siga.util.HibernateThreadFilter.doFiltro(HibernateThreadFilter.java:135) [classes:]
        at br.gov.jfrj.siga.util.HibernateThreadFilter.executaFiltro(HibernateThreadFilter.java:126) [classes:]
        at br.gov.jfrj.siga.util.HibernateThreadFilter.doFilter(HibernateThreadFilter.java:61) [classes:]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Fina  l-redhat-1]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat  -1]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:499) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.3.3.Final-redhat-3.j  ar:7.3.3.Final-redhat-3]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final  -redhat-1]
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_79]

16:09:26,409 INFO  [br.gov.jfrj.siga.util.HibernateThreadFilter] (http-/0.0.0.0:8680-2) Ocorreu um erro durante a execução da operação: /WEB-INF/page/prin  cipal/principal.jsp raised an exception
16:09:26,412 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/siga].[default]] (http-/0.0.0.0:8680-2) JBWEB000236: Servlet.servi  ce() for servlet default threw exception: java.lang.NoClassDefFoundError: org/apache/jsp/tag/meta/http_003a/localhost/jeetags/pagina_tag
        at org.apache.jsp.WEB_002dINF.page.principal.principal_jsp._jspx_meth_siga_005fpagina_005f0(principal_jsp.java:106)
        at org.apache.jsp.WEB_002dINF.page.principal.principal_jsp._jspService(principal_jsp.java:83)
--
        at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.interceptor.ResourceLookupInterceptor.intercept(ResourceLookupInterceptor.java:69) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.core.EnhancedRequestExecution.execute(EnhancedRequestExecution.java:44) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.VRaptor$1.insideRequest(VRaptor.java:95) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.ioc.guice.GuiceProvider.provideForRequest(GuiceProvider.java:82) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:101) [vraptor-3.5.4.jar:]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Fina  l-redhat-1]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat  -1]
        at br.gov.jfrj.siga.util.HibernateThreadFilter.doFiltro(HibernateThreadFilter.java:135) [classes:]
        at br.gov.jfrj.siga.util.HibernateThreadFilter.executaFiltro(HibernateThreadFilter.java:126) [classes:]
        at br.gov.jfrj.siga.util.HibernateThreadFilter.doFilter(HibernateThreadFilter.java:61) [classes:]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Fina  l-redhat-1]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat  -1]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:499) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.3.3.Final-redhat-3.j  ar:7.3.3.Final-redhat-3]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final  -redhat-1]
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_79]


```

**Comment by Markenson** [comment]
A intermitência se deve ao fato que este erro está escondendo ("engolindo") outras exceções, dando a falsa sensação que ocorre de forma aleatória. Provavelmente outros erros ocorrem, mas sempre são exibidos como o mesmo erro.
