### ISSUE TITLE
IDP: FileNotFoundException (/sigaidp/hosted/)

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#504]
O erro abaixo que apareceu nos ambientes de homologacao e canario também ocorreu no meu ambiente de desenvolvimento. 

```
13:20:38,588 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/sigaidp].[default]] (http-/0.0.0.0:8080-4) JBWEB000236: Servlet.service() for servlet default threw exception: java.io.FileNotFoundException: JBWEB000088: The requested resource (/sigaidp/hosted/) is not available
	at org.apache.catalina.servlets.DefaultServlet.serveResource(DefaultServlet.java:651) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.servlets.DefaultServlet.doGet(DefaultServlet.java:338) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.servlets.DefaultServlet.doPost(DefaultServlet.java:374) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:754) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-1.jar:1.0.2.Final-redhat-1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-1.jar:1.0.2.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:832) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:718) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:655) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.picketlink.identity.federation.bindings.tomcat.idp.AbstractIDPValve.includeResource(AbstractIDPValve.java:417) [picketlink-jbas7-2.1.9.SP3-redhat-1.jar:2.1.9.SP3-redhat-1]
	at org.picketlink.identity.federation.bindings.tomcat.idp.AbstractIDPValve.forwardHosted(AbstractIDPValve.java:398) [picketlink-jbas7-2.1.9.SP3-redhat-1.jar:2.1.9.SP3-redhat-1]
	at org.picketlink.identity.federation.bindings.tomcat.idp.AbstractIDPValve.handleSAMLMessage(AbstractIDPValve.java:369) [picketlink-jbas7-2.1.9.SP3-redhat-1.jar:2.1.9.SP3-redhat-1]
	at org.picketlink.identity.federation.bindings.tomcat.idp.AbstractIDPValve.invoke(AbstractIDPValve.java:319) [picketlink-jbas7-2.1.9.SP3-redhat-1.jar:2.1.9.SP3-redhat-1]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_71]

13:20:38,589 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/sigaidp].[default]] (http-/0.0.0.0:8080-3) JBWEB000236: Servlet.service() for servlet default threw exception: java.io.FileNotFoundException: JBWEB000088: The requested resource (/sigaidp/hosted/) is not available
	at org.apache.catalina.servlets.DefaultServlet.serveResource(DefaultServlet.java:651) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.servlets.DefaultServlet.doGet(DefaultServlet.java:338) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.servlets.DefaultServlet.doPost(DefaultServlet.java:374) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:754) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-1.jar:1.0.2.Final-redhat-1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-1.jar:1.0.2.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:832) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:718) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:655) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.picketlink.identity.federation.bindings.tomcat.idp.AbstractIDPValve.includeResource(AbstractIDPValve.java:417) [picketlink-jbas7-2.1.9.SP3-redhat-1.jar:2.1.9.SP3-redhat-1]
	at org.picketlink.identity.federation.bindings.tomcat.idp.AbstractIDPValve.forwardHosted(AbstractIDPValve.java:398) [picketlink-jbas7-2.1.9.SP3-redhat-1.jar:2.1.9.SP3-redhat-1]
	at org.picketlink.identity.federation.bindings.tomcat.idp.AbstractIDPValve.handleSAMLMessage(AbstractIDPValve.java:369) [picketlink-jbas7-2.1.9.SP3-redhat-1.jar:2.1.9.SP3-redhat-1]
	at org.picketlink.identity.federation.bindings.tomcat.idp.AbstractIDPValve.invoke(AbstractIDPValve.java:319) [picketlink-jbas7-2.1.9.SP3-redhat-1.jar:2.1.9.SP3-redhat-1]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_71]

13:20:38,588 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/sigaidp].[default]] (http-/0.0.0.0:8080-5) JBWEB000236: Servlet.service() for servlet default threw exception: java.io.FileNotFoundException: JBWEB000088: The requested resource (/sigaidp/hosted/) is not available
	at org.apache.catalina.servlets.DefaultServlet.serveResource(DefaultServlet.java:651) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.servlets.DefaultServlet.doGet(DefaultServlet.java:338) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.servlets.DefaultServlet.doPost(DefaultServlet.java:374) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:754) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-1.jar:1.0.2.Final-redhat-1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-1.jar:1.0.2.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:832) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:718) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:655) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.picketlink.identity.federation.bindings.tomcat.idp.AbstractIDPValve.includeResource(AbstractIDPValve.java:417) [picketlink-jbas7-2.1.9.SP3-redhat-1.jar:2.1.9.SP3-redhat-1]
	at org.picketlink.identity.federation.bindings.tomcat.idp.AbstractIDPValve.forwardHosted(AbstractIDPValve.java:398) [picketlink-jbas7-2.1.9.SP3-redhat-1.jar:2.1.9.SP3-redhat-1]
	at org.picketlink.identity.federation.bindings.tomcat.idp.AbstractIDPValve.handleSAMLMessage(AbstractIDPValve.java:369) [picketlink-jbas7-2.1.9.SP3-redhat-1.jar:2.1.9.SP3-redhat-1]
	at org.picketlink.identity.federation.bindings.tomcat.idp.AbstractIDPValve.invoke(AbstractIDPValve.java:319) [picketlink-jbas7-2.1.9.SP3-redhat-1.jar:2.1.9.SP3-redhat-1]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_71]

13:20:38,588 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/sigaidp].[default]] (http-/0.0.0.0:8080-8) JBWEB000236: Servlet.service() for servlet default threw exception: java.io.FileNotFoundException: JBWEB000088: The requested resource (/sigaidp/hosted/) is not available
	at org.apache.catalina.servlets.DefaultServlet.serveResource(DefaultServlet.java:651) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.servlets.DefaultServlet.doGet(DefaultServlet.java:338) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.servlets.DefaultServlet.doPost(DefaultServlet.java:374) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:754) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-1.jar:1.0.2.Final-redhat-1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-1.jar:1.0.2.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:832) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:718) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:655) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.picketlink.identity.federation.bindings.tomcat.idp.AbstractIDPValve.includeResource(AbstractIDPValve.java:417) [picketlink-jbas7-2.1.9.SP3-redhat-1.jar:2.1.9.SP3-redhat-1]
	at org.picketlink.identity.federation.bindings.tomcat.idp.AbstractIDPValve.forwardHosted(AbstractIDPValve.java:398) [picketlink-jbas7-2.1.9.SP3-redhat-1.jar:2.1.9.SP3-redhat-1]
	at org.picketlink.identity.federation.bindings.tomcat.idp.AbstractIDPValve.handleSAMLMessage(AbstractIDPValve.java:369) [picketlink-jbas7-2.1.9.SP3-redhat-1.jar:2.1.9.SP3-redhat-1]
	at org.picketlink.identity.federation.bindings.tomcat.idp.AbstractIDPValve.invoke(AbstractIDPValve.java:319) [picketlink-jbas7-2.1.9.SP3-redhat-1.jar:2.1.9.SP3-redhat-1]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.3.3.Final-redhat-3.jar:7.3.3.Final-redhat-3]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.3.0.Final-redhat-1.jar:7.3.0.Final-redhat-1]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_71]
```

**Comment by Markenson** [comment]
O erro só ocorre após fazer o login via Internet Explorer.

**Comment by Markenson** [comment]
O erro ocorre na carga do sigawf e sigagc.

**Comment by Markenson** [comment]
O problema é causado pela falta de definição do welcome-file no web.xml, conforme instruções de [configuração do IDP](https://docs.jboss.org/author/display/PLINK/Identity+Provider+Configuration)


![image](https://cloud.githubusercontent.com/assets/2985140/11444882/ca2a63fe-950e-11e5-829d-131dff65a862.png)

**Comment by Markenson** [comment]
Reabrindo issue, pois problema voltou a ocorrer (inclusive nos outros módulos)

**Comment by Markenson** [comment]
Para o IDP resolvido no commit 539a7f2ede1d42f066328cb1c3cd
