### ISSUE TITLE
SR: Busca está travando (pending) quando o órgão tem só duas letras.

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#570]
Testado com RJ-SR-2016/95918.

@Markenson , o que acontece quando a requisição fica (pending) por muito tempo? Transaction reaper?!?

**Comment by crivano** [comment]
Na verdade o erro é esse aqui:

```
14:13:34,036 INFO  [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 2) JBAS015018: A implantação siga.war foi implantada anteriormente por este scanner, mas foi removida da lista da implantação do servidor por outra ferramenta de gerenciamento. O arquivo marcador C:\Desenvolvimento\jboss-eap-6.2.3\standalone\deployments\siga.war.undeployed foi adicionado para gravar este fato.
14:13:34,037 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/sigasr].[default]] (http-/0.0.0.0:8080-5) JBWEB000236: Servlet.service() for servlet default threw exception: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:2271) [rt.jar:1.7.0_71]
	at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:178) [rt.jar:1.7.0_71]
	at org.hibernate.type.descriptor.java.DataHelper.extractBytes(DataHelper.java:205) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.type.descriptor.java.PrimitiveByteArrayTypeDescriptor.wrap(PrimitiveByteArrayTypeDescriptor.java:125) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.type.descriptor.java.PrimitiveByteArrayTypeDescriptor.wrap(PrimitiveByteArrayTypeDescriptor.java:42) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.type.descriptor.sql.BlobTypeDescriptor$1.doExtract(BlobTypeDescriptor.java:64) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:64) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:261) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:247) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:332) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:2926) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1673) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1605) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.loader.Loader.getRow(Loader.java:1505) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:713) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.loader.Loader.processResultSet(Loader.java:943) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.loader.Loader.doQuery(Loader.java:911) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:342) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:312) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.loader.Loader.loadEntityBatch(Loader.java:2207) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.loader.entity.LegacyBatchingEntityLoaderBuilder$LegacyBatchingEntityLoader.load(LegacyBatchingEntityLoaderBuilder.java:108) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3941) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:460) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:429) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:206) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:262) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:150) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1098) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:1025) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:671) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.type.EntityType.resolve(EntityType.java:489) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
```

**Comment by raphaelpaiva** [comment]
A busca faz acabar a memória?

**Comment by crivano** [comment]
O query estava gerando um SELECT * FROM...

Já corrigi.

**Comment by Markenson** [comment]
@crivano Qualquer requisição que demore além do tempo dá problema de transaction reaper.

**Comment by raphaelpaiva** [comment]
A gerência de transações é feita na mão ou é delegada para o container?

**Comment by raphaelpaiva** [comment]
No canário, não ocorre um problema do TransactionReaper desde o dia 29/12/2015. Não atingimos os usuários que utilizam as partes dos sistemas que são mais propícias a dar ou a carga está baixa?

**Comment by crivano** [comment]
@raphaelpaiva , acho que para corrigirmos o problema do transaction reaper, ele precisa estar ocorrendo. Pelo visto, só conseguiremos aumentando a carga. Detalhe: pode ser que nem ocorra na versão vRaptor, ou que seja muito raro...

**Comment by Markenson** [comment]
@raphaelpaiva as transações de banco sõa gerenciadas pela aplicação. Mas o jboss coloca todas as transações em uma transação global gerenciada por ele. Quando ocorre um request demorado que explora o timeout, por exemplo, ocorre o transaction reaper.

Uma maneira de saber se ainda ocorre é colocar um timeout mais baixo (o default são 5 minutos).
