### ISSUE TITLE
Doc: Erros ao acessar documentos

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#572]
Ao substituir uma lotação extinta - exemplo: SESAU (extinta) -, e tentar acessar documentos desta lotação, o sistema apresenta os seguintes erros:

1 - Log de erro ao tentar acessar documentos da lotação na situação "em elaboração":

your controller raised an exception

Found shared references to a collection: br.gov.jfrj.siga.ex.ExDocumento.exBoletimDocSet

javax.servlet.ServletException: your controller raised an exception
	at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:105)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at br.gov.jfrj.siga.hibernate.ExThreadFilter.doFiltro(ExThreadFilter.java:106)
	at br.gov.jfrj.siga.hibernate.ExThreadFilter.executaFiltro(ExThreadFilter.java:97)
	at br.gov.jfrj.siga.hibernate.ExThreadFilter.doFilter(ExThreadFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:499)
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.HibernateException: Found shared references to a collection: br.gov.jfrj.siga.ex.ExDocumento.exBoletimDocSet
	at org.hibernate.engine.internal.Collections.processReachableCollection(Collections.java:177)
	at org.hibernate.event.internal.FlushVisitor.processCollection(FlushVisitor.java:59)
	at org.hibernate.event.internal.AbstractVisitor.processValue(AbstractVisitor.java:121)
	at org.hibernate.event.internal.AbstractVisitor.processValue(AbstractVisitor.java:82)
	at org.hibernate.event.internal.AbstractVisitor.processEntityPropertyValues(AbstractVisitor.java:76)
	at org.hibernate.event.internal.DefaultFlushEntityEventListener.onFlushEntity(DefaultFlushEntityEventListener.java:175)
	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEntities(AbstractFlushingEventListener.java:228)
	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:100)
	at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:58)
	at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1211)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1661)
	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:374)
	at br.gov.jfrj.siga.model.dao.ModeloDao.findAndCacheByCriteria(ModeloDao.java:216)
	at br.gov.jfrj.siga.dp.dao.CpDao.listarMarcadores(CpDao.java:1985)
	at br.gov.jfrj.siga.vraptor.ExSelecionavelController.getEstados(ExSelecionavelController.java:49)
	at br.gov.jfrj.siga.vraptor.ExMobilController.aListar(ExMobilController.java:266)
	at sun.reflect.GeneratedMethodAccessor2949.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at br.com.caelum.vraptor.interceptor.ExecuteMethodInterceptor.intercept(ExecuteMethodInterceptor.java:61)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.ParametersInstantiatorInterceptor.intercept(ParametersInstantiatorInterceptor.java:96)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:59)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.InstantiateInterceptor.intercept(InstantiateInterceptor.java:48)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:56)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.ExceptionHandlerInterceptor.intercept(ExceptionHandlerInterceptor.java:67)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:56)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.util.jpa.JPATransactionInterceptor.intercept(JPATransactionInterceptor.java:54)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.gov.jfrj.siga.vraptor.CacheControlInterceptor.intercept(CacheControlInterceptor.java:44)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.ResourceLookupInterceptor.intercept(ResourceLookupInterceptor.java:69)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.EnhancedRequestExecution.execute(EnhancedRequestExecution.java:44)
	at br.com.caelum.vraptor.VRaptor$1.insideRequest(VRaptor.java:95)
	at br.com.caelum.vraptor.ioc.guice.GuiceProvider.provideForRequest(GuiceProvider.java:82)
	at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:101)
	... 19 more

2 - Log de erro ao tentar acessar documentos da lotação nas situações "aguardando andamento", "transferido", "arquivado":

your controller raised an exception

Exception occurred inside getter of br.gov.jfrj.siga.ex.ExDocumento.exNivelAcesso

javax.servlet.ServletException: your controller raised an exception
	at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:105)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at br.gov.jfrj.siga.hibernate.ExThreadFilter.doFiltro(ExThreadFilter.java:106)
	at br.gov.jfrj.siga.hibernate.ExThreadFilter.executaFiltro(ExThreadFilter.java:97)
	at br.gov.jfrj.siga.hibernate.ExThreadFilter.doFilter(ExThreadFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:499)
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.PropertyAccessException: Exception occurred inside getter of br.gov.jfrj.siga.ex.ExDocumento.exNivelAcesso
	at org.hibernate.property.BasicPropertyAccessor$BasicGetter.get(BasicPropertyAccessor.java:167)
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.getPropertyValues(AbstractEntityTuplizer.java:609)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.getPropertyValues(PojoEntityTuplizer.java:392)
	at org.hibernate.persister.entity.AbstractEntityPersister.getPropertyValues(AbstractEntityPersister.java:4531)
	at org.hibernate.event.internal.DefaultFlushEntityEventListener.getValues(DefaultFlushEntityEventListener.java:198)
	at org.hibernate.event.internal.DefaultFlushEntityEventListener.onFlushEntity(DefaultFlushEntityEventListener.java:157)
	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEntities(AbstractFlushingEventListener.java:228)
	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:100)
	at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:58)
	at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1211)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1661)
	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:374)
	at br.gov.jfrj.siga.model.dao.ModeloDao.findAndCacheByCriteria(ModeloDao.java:216)
	at br.gov.jfrj.siga.dp.dao.CpDao.listarMarcadores(CpDao.java:1985)
	at br.gov.jfrj.siga.vraptor.ExSelecionavelController.getEstados(ExSelecionavelController.java:49)
	at br.gov.jfrj.siga.vraptor.ExMobilController.aListar(ExMobilController.java:266)
	at sun.reflect.GeneratedMethodAccessor2949.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at br.com.caelum.vraptor.interceptor.ExecuteMethodInterceptor.intercept(ExecuteMethodInterceptor.java:61)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.ParametersInstantiatorInterceptor.intercept(ParametersInstantiatorInterceptor.java:96)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:59)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.InstantiateInterceptor.intercept(InstantiateInterceptor.java:48)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:56)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.ExceptionHandlerInterceptor.intercept(ExceptionHandlerInterceptor.java:67)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:56)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.util.jpa.JPATransactionInterceptor.intercept(JPATransactionInterceptor.java:54)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.gov.jfrj.siga.vraptor.CacheControlInterceptor.intercept(CacheControlInterceptor.java:44)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.interceptor.ResourceLookupInterceptor.intercept(ResourceLookupInterceptor.java:69)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
	at br.com.caelum.vraptor.core.EnhancedRequestExecution.execute(EnhancedRequestExecution.java:44)
	at br.com.caelum.vraptor.VRaptor$1.insideRequest(VRaptor.java:95)
	at br.com.caelum.vraptor.ioc.guice.GuiceProvider.provideForRequest(GuiceProvider.java:82)
	at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:101)
	... 19 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor809.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.hibernate.property.BasicPropertyAccessor$BasicGetter.get(BasicPropertyAccessor.java:164)
	... 72 more
Caused by: org.hibernate.HibernateException: Found shared references to a collection: br.gov.jfrj.siga.ex.ExDocumento.exBoletimDocSet
	at org.hibernate.engine.internal.Collections.processReachableCollection(Collections.java:177)
	at org.hibernate.event.internal.FlushVisitor.processCollection(FlushVisitor.java:59)
	at org.hibernate.event.internal.AbstractVisitor.processValue(AbstractVisitor.java:121)
	at org.hibernate.event.internal.AbstractVisitor.processValue(AbstractVisitor.java:82)
	at org.hibernate.event.internal.AbstractVisitor.processEntityPropertyValues(AbstractVisitor.java:76)
	at org.hibernate.event.internal.DefaultFlushEntityEventListener.onFlushEntity(DefaultFlushEntityEventListener.java:175)
	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEntities(AbstractFlushingEventListener.java:228)
	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:100)
	at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:58)
	at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1211)
	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:1828)
	at org.hibernate.internal.AbstractSessionImpl.list(AbstractSessionImpl.java:231)
	at org.hibernate.internal.SQLQueryImpl.list(SQLQueryImpl.java:157)
	at br.gov.jfrj.siga.dp.dao.CpDao.consultarDataEHoraDoServidor(CpDao.java:1307)
	at br.gov.jfrj.siga.dp.dao.CpDao.dt(CpDao.java:1341)
	at br.gov.jfrj.siga.dp.dao.CpDao.gravar(CpDao.java:1578)
	at br.gov.jfrj.siga.ex.bl.ExBL.atualizarDnmNivelAcesso(ExBL.java:4102)
	at br.gov.jfrj.siga.ex.ExDocumento.getExNivelAcesso(ExDocumento.java:123)
	... 76 more

**Comment by Chrystinne** [comment]
Este erro (your controller raised an exception
Exception occurred inside getter of br.gov.jfrj.siga.ex.ExDocumento.exNivelAcesso) é mais genérico e ocorre ao listar documentos de uma determinada lotação, que não precisa estar extinta. 

Como reproduzir: 

Substituindo a CIPE, acessar o link: http://siga/sigaex/app/expediente/doc/listar?popup=&propriedade=&postback=1&apenasRefresh=0&paramoffset=150&p.offset=150&ultMovIdEstadoDoc=6&ordem=0&visualizacao=0&ultMovTipoResp=2&requltMovRespSel=&alterouSel=&ultMovRespSel.id=&ultMovRespSel.descricao=&ultMovRespSel.buscar=&ultMovRespSel.sigla=&requltMovLotaRespSel=&alterouSel=&ultMovLotaRespSel.id=23508&ultMovLotaRespSel.descricao=COORDENADORIA+DE+INFORMA%C3%87%C3%83O+E+PRODU%C3%87%C3%83O+EDITORIAL&ultMovLotaRespSel.buscar=&ultMovLotaRespSel.sigla=CIPE&orgaoUsu=0&idTpDoc=0&dtDocString=&dtDocFinalString=&idTipoFormaDoc=1&forma=0&idMod=0&anoEmissaoString=0&numExpediente=&numExtDoc=&reqcpOrgaoSel=&alterouSel=&cpOrgaoSel.id=&cpOrgaoSel.descricao=&cpOrgaoSel.buscar=&cpOrgaoSel.sigla=&numAntigoDoc=&reqsubscritorSel=&alterouSel=&subscritorSel.id=&subscritorSel.descricao=&subscritorSel.buscar=&subscritorSel.sigla=&tipoCadastrante=1&reqcadastranteSel=&alterouSel=&cadastranteSel.id=&cadastranteSel.descricao=&cadastranteSel.buscar=&cadastranteSel.sigla=&reqlotaCadastranteSel=&alterouSel=&lotaCadastranteSel.id=&lotaCadastranteSel.descricao=&lotaCadastranteSel.buscar=&lotaCadastranteSel.sigla=&tipoDestinatario=2&reqdestinatarioSel=&alterouSel=&destinatarioSel.id=&destinatarioSel.descricao=&destinatarioSel.buscar=&destinatarioSel.sigla=&reqlotacaoDestinatarioSel=&alterouSel=&lotacaoDestinatarioSel.id=&lotacaoDestinatarioSel.descricao=&lotacaoDestinatarioSel.buscar=&lotacaoDestinatarioSel.sigla=&reqorgaoExternoDestinatarioSel=&alterouSel=&orgaoExternoDestinatarioSel.id=&orgaoExternoDestinatarioSel.descricao=&orgaoExternoDestinatarioSel.buscar=&orgaoExternoDestinatarioSel.sigla=&nmDestinatario=&reqclassificacaoSel=&alterouSel=&classificacaoSel.id=&classificacaoSel.descricao=&classificacaoSel.buscar=&classificacaoSel.sigla=&descrDocumento=&fullText=

**Comment by crivano** [comment]
Fechado pois é o mesmo que o #510
