### ISSUE TITLE
SR: NPE ao exibir arquivos

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#591]
```
14:52:50,946 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/sigasr].[default]] (http-/0.0.0.0:8080-5) JBWEB000236: Servlet.service() for servlet default threw exception: java.lang.NullPointerException
        at br.gov.jfrj.siga.sr.model.SrSolicitacao.getArquivosAnexos(SrSolicitacao.java:1116) [classes:]
        at br.gov.jfrj.siga.sr.vraptor.SolicitacaoController.exibir(SolicitacaoController.java:380) [classes:]
        at sun.reflect.GeneratedMethodAccessor1897.invoke(Unknown Source) [:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_71]
        at br.com.caelum.vraptor.interceptor.ExecuteMethodInterceptor.intercept(ExecuteMethodInterceptor.java:61) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.interceptor.InstantiateInterceptor.intercept(InstantiateInterceptor.java:48) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.interceptor.ParametersInstantiatorInterceptor.intercept(ParametersInstantiatorInterceptor.java:96) [vraptor-3.5.4.jar:]
        at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:59) [vraptor-3.5.4.jar:]
```

**Comment by rafaela00castro** [comment]
Resolvido no commit [fc556db]. Foi criada a solicitação TRF2-SR-2016/19853 para criar validação no processo de anexação para evitar arquivo nulo nessa movimentação.
