### ISSUE TITLE
SR: LazyInitializationException ao notificar atendente por e-mail

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#650]
ERROR [br.gov.jfrj.siga.sr.model.SrMovimentacao](http-/0.0.0.0:8080-10) Erro ao notificar: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: br.gov.jfrj.siga.dp.DpPessoa.pessoasPosteriores, could not initialize proxy - no Session
    at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:566) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
    at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:186) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
    at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:545) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
    at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:124) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
    at org.hibernate.collection.internal.PersistentSet.iterator(PersistentSet.java:180) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
    at br.gov.jfrj.siga.dp.DpPessoa.getPessoaAtual(DpPessoa.java:419) [siga-cp-1.2-SNAPSHOT.jar:]
    at br.gov.jfrj.siga.sr.model.SrMovimentacao.getEmailsNotificacaoAtendende(SrMovimentacao.java:772) [classes:]
    at br.gov.jfrj.siga.sr.notifiers.Correio.notificarAtendente(Correio.java:43) [classes:]
    at br.gov.jfrj.siga.sr.model.SrMovimentacao.notificarAtendente(SrMovimentacao.java:477) [classes:]
    at br.gov.jfrj.siga.sr.model.SrMovimentacao.salvarAtualizandoSolicitacao(SrMovimentacao.java:308) [classes:]
    at br.gov.jfrj.siga.sr.model.SrMovimentacao.salvar(SrMovimentacao.java:284) [classes:]
    at br.gov.jfrj.siga.sr.vraptor.SolicitacaoController.darAndamento(SolicitacaoController.java:826) [classes:]

**Comment by esredson** [comment]
ERROR [br.gov.jfrj.siga.sr.model.SrMovimentacao] (http-/0.0.0.0:8080-1) Erro ao notificar: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: br.gov.jfrj.siga.dp.DpLotacao.lotacoesPosteriores, could not initialize proxy - no Session
	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:566) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:186) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:545) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:124) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.collection.internal.PersistentSet.iterator(PersistentSet.java:180) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at br.gov.jfrj.siga.dp.DpLotacao.getLotacaoAtual(DpLotacao.java:346) [siga-cp-1.2-SNAPSHOT.jar:]
	at br.gov.jfrj.siga.sr.model.SrSolicitacao.getSubstitutos(SrSolicitacao.java:2030) [classes:]
	at br.gov.jfrj.siga.sr.model.SrMovimentacao.getEmailsNotificacaoAtendende(SrMovimentacao.java:777) [classes:]
	at br.gov.jfrj.siga.sr.notifiers.Correio.notificarAtendente(Correio.java:43) [classes:]
	at br.gov.jfrj.siga.sr.model.SrMovimentacao.notificarAtendente(SrMovimentacao.java:477) [classes:]
	at br.gov.jfrj.siga.sr.model.SrMovimentacao.salvarAtualizandoSolicitacao(SrMovimentacao.java:308) [classes:]
	at br.gov.jfrj.siga.sr.model.SrMovimentacao.salvar(SrMovimentacao.java:284) [classes:]
	at br.gov.jfrj.siga.sr.model.SrSolicitacao.iniciarAtendimento(SrSolicitacao.java:2181) [classes:]
	at br.gov.jfrj.siga.sr.model.SrSolicitacao.salvarComHistorico(SrSolicitacao.java:1537) [classes:]
	at br.gov.jfrj.siga.sr.model.SrSolicitacao.salvar(SrSolicitacao.java:1475) [classes:]
	at br.gov.jfrj.siga.sr.model.SrSolicitacao.escalonarCriandoFilha(SrSolicitacao.java:2255) [classes:]
	at br.gov.jfrj.siga.sr.vraptor.SolicitacaoController.escalonarGravar(SolicitacaoController.java:690) [classes:]

**Comment by raphaelpaiva** [comment]
Bump! Voltou a aparecer no log.

**Comment by Chrystinne** [comment]
A não ser que seja um caso bastante específico que não consegui reproduzir, esse erro não ocorre mais. Testado em desenvolvimento.
