### ISSUE TITLE
SR: LazyInitializationException ao gravar solicitação

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#652]
ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/sigasr].[default]] (http-/0.0.0.0:8080-1) JBWEB000236: Servlet.service() for servlet default threw exception: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: br.gov.jfrj.siga.dp.DpLotacao.lotacoesPosteriores, could not initialize proxy - no Session
	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:566) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:186) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:545) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:124) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at org.hibernate.collection.internal.PersistentSet.iterator(PersistentSet.java:180) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at br.gov.jfrj.siga.dp.DpLotacao.isFechada(DpLotacao.java:74) [siga-cp-1.2-SNAPSHOT.jar:]
	at br.gov.jfrj.siga.dp.DpLotacao.getSigla(DpLotacao.java:139) [siga-cp-1.2-SNAPSHOT.jar:]
	at sun.reflect.GeneratedMethodAccessor834.invoke(Unknown Source) [:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_71]
	at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_71]
	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:192) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
	at br.gov.jfrj.siga.dp.DpLotacao_$$_jvst7ff_d8.getSigla(DpLotacao_$$_jvst7ff_d8.java) [siga-cp-1.2-SNAPSHOT.jar:]
	at br.gov.jfrj.siga.sr.model.SrIntervaloEmAtendimento.setHorario(SrIntervaloEmAtendimento.java:102) [classes:]
	at br.gov.jfrj.siga.sr.model.SrSolicitacao.getTrechosNaoPendentesPorEtapa(SrSolicitacao.java:780) [classes:]
	at br.gov.jfrj.siga.sr.model.SrSolicitacao.getCadastro(SrSolicitacao.java:2576) [classes:]
	at br.gov.jfrj.siga.sr.model.SrSolicitacao.salvarComHistorico(SrSolicitacao.java:1509) [classes:]
	at br.gov.jfrj.siga.sr.model.SrSolicitacao.salvar(SrSolicitacao.java:1475) [classes:]
	at br.gov.jfrj.siga.sr.vraptor.SolicitacaoController.gravar(SolicitacaoController.java:299) [classes:]

**Comment by raphaelpaiva** [comment]
+1
Também ocorre no sigagc. Parece ocorrer sempre no uso de alguma funcionalidade. Estou acompanhando os logs aqui e aparece recorrentemente, provavelmente alguém tentando fazer algo várias vezes, sem sucesso. Em anexo a stacktrace.

[lazyInstatitiationSigaGC.txt](https://github.com/projeto-siga/siga/files/161479/lazyInstatitiationSigaGC.txt)

**Comment by esredson** [comment]
Ver #1081
