### ISSUE TITLE
SR: TransientPropertyValueException ao vincular solicitação

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#653]
ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/sigasr].[default]](http-/0.0.0.0:8080-12) JBWEB000236: Servlet.service() for servlet default threw exception: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing: br.gov.jfrj.siga.sr.model.SrMovimentacao.solicitacaoReferencia -> br.gov.jfrj.siga.sr.model.SrSolicitacao
    at org.hibernate.engine.spi.CascadingAction$8.noCascade(CascadingAction.java:380) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
    at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:176) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
    at org.hibernate.event.internal.AbstractFlushingEventListener.cascadeOnFlush(AbstractFlushingEventListener.java:162) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
    at org.hibernate.event.internal.AbstractFlushingEventListener.prepareEntityFlushes(AbstractFlushingEventListener.java:153) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
    at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:89) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
    at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:51) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
    at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1240) [hibernate-core-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
    at org.hibernate.ejb.AbstractEntityManagerImpl.flush(AbstractEntityManagerImpl.java:996) [hibernate-entitymanager-4.2.7.SP4-redhat-1.jar:4.2.7.SP4-redhat-1]
    at br.gov.jfrj.siga.model.Objeto.save(Objeto.java:117) [siga-base-1.2-SNAPSHOT.jar:]
    at br.gov.jfrj.siga.sr.model.SrMovimentacao.salvarAtualizandoSolicitacao(SrMovimentacao.java:294) [classes:]
    at br.gov.jfrj.siga.sr.model.SrMovimentacao.salvar(SrMovimentacao.java:284) [classes:]
    at br.gov.jfrj.siga.sr.model.SrSolicitacao.vincular(SrSolicitacao.java:2483) [classes:]
    at br.gov.jfrj.siga.sr.vraptor.SolicitacaoController.vincular(SolicitacaoController.java:706) [classes:]

**Comment by Chrystinne** [comment]
Testei em desenvolvimento e não está ocorrendo mais.
