### ISSUE TITLE
CP-SINC: Erro ao importar XML

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#732]
O seguinte erro está ocorrendo ao tentar importar o XML apontando para a versão 5.x:

```
br.gov.jfrj.siga.base.AplicacaoException: XML não contém cargo!
        at br.gov.jfrj.importar.SigaCpSinc.importarXml(SigaCpSinc.java:847)
        at br.gov.jfrj.importar.SigaCpSinc.importxml(SigaCpSinc.java:553)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at br.gov.jfrj.importar.SigaCpSinc.run(SigaCpSinc.java:481)
        at br.gov.jfrj.importar.SigaCpSinc.main(SigaCpSinc.java:449)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:313)
        at com.simontuffs.onejar.Boot.main(Boot.java:161)
Mar 16, 2016 6:00:13 PM br.gov.jfrj.importar.SigaCpSinc log
WARNING: XML não contém cargo!

```

**Comment by Markenson** [comment]
Na verdade o problema é que a máquina que roda o sincronismo não aponta para o canário (bastou definir o nome correto da máquina para funcionar)
