### ISSUE TITLE
GC: lazy exception ao listar conhecimentos de lotação fechada

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#783]
Caused by: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: br.gov.jfrj.siga.dp.DpLotacao.lotacoesPosteriores, could not initialize proxy - no Session
    at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:566)
    at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:186)
    at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:545)
    at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:124)
    at org.hibernate.collection.internal.PersistentSet.iterator(PersistentSet.java:180)
    at br.gov.jfrj.siga.dp.DpLotacao.isFechada(DpLotacao.java:74)
    at br.gov.jfrj.siga.dp.DpLotacao.getSigla(DpLotacao.java:139)
    at sun.reflect.GeneratedMethodAccessor879.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:192)
    at br.gov.jfrj.siga.dp.DpLotacao_$$_jvstc0f_8e.getSigla(DpLotacao_$$_jvstc0f_8e.java)
    ... 115 more

**Comment by Chrystinne** [comment]
@esredson Não estou conseguindo reproduzir o erro. Poderia colocar aqui como você está fazendo para listar, por favor? Uma coisa que percebi é que a busca do GC não contempla lotações extintas. Se buscarmos uma lotação extinta nos campos "Autor" ou "Responsável", o sistema não retorna nada.

**Comment by Chrystinne** [comment]
Estou conseguindo listando e acessar conhecimentos de lotação extinta. Acho que pode ter ocorrido
um erro específico de algum(a) conhecimento/lotação. Vou ver se consigo seguindo os mesmos passos que @esredson usou pra ter esse erro.

![captura_de_tela_041516_063039_pm](https://cloud.githubusercontent.com/assets/4949149/14575436/28403e04-0338-11e6-9e92-617bc1e983d6.jpg)

**Comment by Chrystinne** [comment]
Não consigo reproduzir este erro. Listei e acessei conhecimentos de lotação extinta sem problemas.
