### ISSUE TITLE
GI: Erro ao acessar webservice "acessos"

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#807]
O seguinte erro ocorre ao tentar acessar o serviço "acessos". (Confirmado no ambiente de homologação)

```
[Server:siga-server01] Caused by: java.lang.NullPointerException
[Server:siga-server01]  at br.gov.jfrj.siga.model.dao.ModeloDao.findByCriteria(ModeloDao.java:209) [siga-base-1.2-SNAPSHOT.jar:]
[Server:siga-server01]  at br.gov.jfrj.siga.model.dao.ModeloDao.findByCriteria(ModeloDao.java:199) [siga-base-1.2-SNAPSHOT.jar:]
[Server:siga-server01]  at br.gov.jfrj.siga.dp.dao.CpDao.listarServicos(CpDao.java:1933) [siga-cp-1.2-SNAPSHOT.jar:]

```

**Comment by Markenson** [comment]
O problema era a versão desatualizada no ambiente. Após o deploy, passou a funcionar normalmente.
