### ISSUE TITLE
SR: illegalStateException ao acessar solicitação a partir do link enviado por e-mail

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#812]
Reportado pelo Helder. Ao acessar http://siga/sigasr/solicitacao/exibir?id=89122 e fazer o login, ocorre o erro abaixo. 

javax.servlet.ServletException: java.lang.IllegalStateException
         at br.gov.jfrj.siga.sr.util.SrThreadFilter.doFiltro(SrThreadFilter.java:31)
         at br.gov.jfrj.siga.base.auditoria.filter.ThreadFilter.doFilter(ThreadFilter.java:190)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
         at br.gov.jfrj.siga.base.log.RequestLoggerFilter.doFilter(RequestLoggerFilter.java:25)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231)
         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
         at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.event(JBossWebContext.java:91)
         at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.invoke(JBossWebContext.java:72)
         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:512)
         at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145)
         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)
         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
         at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)
         at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)
         at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926)
         at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException
         at org.apache.catalina.connector.ResponseFacade.sendError(ResponseFacade.java:392)
         at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:152)
         at org.apache.catalina.servlets.DefaultServlet.serveResource(DefaultServlet.java:679)
         at org.apache.catalina.servlets.DefaultServlet.doGet(DefaultServlet.java:363)
         at org.apache.catalina.servlets.DefaultServlet.doPost(DefaultServlet.java:399)
         at javax.servlet.http.HttpServlet.service(HttpServlet.java:754)
         at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
         at br.com.caelum.vraptor.resource.DefaultResourceNotFoundHandler.couldntFind(DefaultResourceNotFoundHandler.java:41)
         at br.com.caelum.vraptor.interceptor.ResourceLookupInterceptor.intercept(ResourceLookupInterceptor.java:71)
         at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
         at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
         at br.com.caelum.vraptor.core.EnhancedRequestExecution.execute(EnhancedRequestExecution.java:44)
         at br.com.caelum.vraptor.VRaptor$1.insideRequest(VRaptor.java:95)
         at br.com.caelum.vraptor.ioc.guice.GuiceProvider.provideForRequest(GuiceProvider.java:82)
         at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:101)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
         at br.gov.jfrj.siga.sr.util.SrThreadFilter.doFiltro(SrThreadFilter.java:28)
         ... 20 more

**Comment by Markenson** [comment]
@adrigrassi Abri o chamado TRF2-SR-2016/25701 para ajustar a propriedade que está causando esse problema.

**Comment by Markenson** [comment]
A propriedade sigasr.url foi alterada conforme abaixo e link passou a funcionar normalmente

de: /sigasr/solicitacao/
para:/sigasr/
