### ISSUE TITLE
GC: ORA-01031 ao acessar conhecimento substituindo lotação

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#816]
Para simular, substituir a lotação à qual pertence o conhecimento TRF2-GC-2015/00338 e tentar acessá-lo usando o campo de busca da barra superior.

Caused by: java.sql.SQLSyntaxErrorException: ORA-01031: privilégios insuficientes

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1044)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1329)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3584)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3665)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1352)
	at org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.executeUpdate(WrappedPreparedStatement.java:493)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:186)
	... 84 more

**Comment by esredson** [comment]
org.hibernate.exception.SQLGrammarException: could not execute statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:82)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:124)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:189)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:59)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3236)
	at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3138)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3468)
	at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:140)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:395)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:387)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:304)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:349)
	at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:67)
	at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1130)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1187)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)
	at br.gov.jfrj.siga.dp.dao.CpDao.consultarPersonalizacao(CpDao.java:973)
	at br.gov.jfrj.siga.acesso.UsuarioAutenticado.carregarUsuario(UsuarioAutenticado.java:105)
	at br.gov.jfrj.siga.acesso.UsuarioAutenticado.carregarUsuarioAutenticado(UsuarioAutenticado.java:160)
	at br.gov.jfrj.siga.vraptor.SigaObjects.carregaPerfil(SigaObjects.java:84)
	at br.gov.jfrj.siga.vraptor.SigaObjects.(SigaObjects.java:50)
	at br.gov.jfrj.siga.vraptor.SigaObjects$$FastClassByGuice$$4b731f40.newInstance()

**Comment by esredson** [comment]
Não ocorre mais hoje.
