### ISSUE TITLE
SR: erro ao gerar relatório 

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#821]
Erro ao gerar relatório com os parâmetros: 
Lotação ESSECAD
Data: 28/04/2016 a 28/04/2016

```
Caused by: java.lang.Exception: String index out of range: 1
	at br.gov.jfrj.siga.sr.reports.SrRelAtendimento.processarDados(SrRelAtendimento.java:153)
	at br.gov.jfrj.relatorio.dinamico.RelatorioTemplate.gerar(RelatorioTemplate.java:202)
	at br.gov.jfrj.siga.sr.vraptor.RelatorioController.gerarRelAtendimentos(RelatorioController.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at br.com.caelum.vraptor.interceptor.ExecuteMethodInterceptor.intercept(ExecuteMethodInterceptor.java:61)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
...	

```

**Comment by rafaela00castro** [comment]
Origem do erro: uma solicitação do Siga-Serviços foi atendida por uma pessoa que tinha um nome fora do padrão: dois espaços em branco entre o sobrenome e o último nome, e isso causa um erro no método ```getPrimeiroNomeEIniciais()``` . Mesmo com a correção do nome da pessoa, não resolveu o erro, pois o método do relatório não faz referencia ao ```getPessoaAtual()```.
